Serialize runtime assumptions
eclipse-openj9/openj9 pull request #11083
Opened 2020-11-02 22:07 UTC by dsouzai

# Overview
Depends on https://github.com/eclipse/omr/pull/5649

This PR adds the infrastructure to serialize/deserialize runtime assumptions. It is a port of some of the code in the `snapshot` branch.

# Design
This is the general design:

`TR_RuntimeAssumptionTable::serialize` is used to serialize runtime assumptions into a buffer. It should be called in `JitShutdown`.
`TR_RuntimeAssumptionTable::deserialize` is used to deserialize runtime assumptions from a buffer. It should be called either sometime before any of the hooks have run, or lazily as the hooks are run.

## Buffer Layout
The buffer is structured in the following way:
```
SerializedDataAtlas
Serialized assumptions for kind 1
Serialized assumptions for kind 2
...
Serialized assumptions for kind n
```
`SerializedDataAtlas` is a table of contents, defined in two new structs in `TR_RuntimeAssumptionTable`:
```
struct AssumptionCountAndSize
      {
      uint32_t _count;
      uint32_t _size;
      };

   struct SerializedDataAtlas
      {
      uint32_t _size;
      AssumptionCountAndSize _numAssumptionsPerKind[LastAssumptionKind];
      };
```
Therefore, `SerializedDataAtlas` contains the size the size of the entire buffer, as well as the number of assumptions serialized + the size of the serialized data for each runtime assumption kind. `TR_RuntimeAssumptionTable::deserialize` can use this data to deserialize the assumptions.

## Serialization
The way `TR_RuntimeAssumptionTable::serialize` serializes the assumptions is:

1. Loop through the runtime assumption kinds
2. Go through all the assumptions for that kind
3. Call the virtual method serialize on the assumption

The owning metadata is the `J9JITexceptionTable` which holds a pointer to the sentinel runtime assumption that is part of the circular linked list of assumptions that belong to a particular JIT'd body. We need to store the owning metadata so that when we add the assumption to the RAT in the restore run, we can also enqueue it into the circular linked list of assumptions for the same JIT'd body.

## Deserialization
The way `TR_RuntimeAssumptionTable::deserialize` works is by looping through all the runtime assumption kinds. For each kind (that's supported), it calls the appropriate static method `deserialize`. The reason `deserialize` is static rather than virtual is because the constructors of the runtime assumptions are protected; therefore, we can't initialize a dummy instance to call a hypothetical virtual `deserialize`.

Therefore, `deserialize` takes a pointer to the start of the section that contains the deserialized assumptions for that kind as well as the number of assumptions in that section. It then loops through the section and calls make to create the runtime assumptions and add it to the RAT.

`TR_RuntimeAssumptionTable::deserialize` also takes an optional parameter `kind`, which can be used to only create assumptions of a specific kind (rather than all kinds).

2020-11-02 22:07 UTC, dsouzai commented
@0xdaryl could you please review?

2020-11-03 17:11 UTC, dsouzai commented on runtime/compiler/runtime/ClassUnloadAssumption.cpp
> +         TR_ASSERT_FATAL(atlas->_numAssumptionsPerKind[k]._count == 0, "Assumption(s) of kind %d serialized!", k);
I was staring at this for a while wondering how this makes sense given that we're going through all the assumptions and calling serialize on them. Then I remembered that in the `snapshot` branch, when running in snapshot mode, we restrict the JIT in a way that results only in the assumptions we expect to be serialized to get created.

This check is, I guess, a way of validating that the compiler isn't generating assumptions we're not expecting to serialize.

2020-11-04 16:05 UTC, dsouzai commented on runtime/compiler/runtime/ClassUnloadAssumption.cpp
> +               TR_PersistentMemory::jitPersistentFree(cursor);
If the plan is to continue running the JVM after taking a snpashot, this shouldn't be done.

2020-11-18 22:26 UTC, dsouzai commented on runtime/compiler/runtime/ClassUnloadAssumption.cpp
> +               TR_PersistentMemory::jitPersistentFree(cursor);
Considering https://github.com/eclipse/openj9/pull/11223 I updated the PR to not free the assumptions anymore.

2020-11-30 21:57 UTC, dsouzai commented
Force pushed again to account for https://github.com/eclipse/openj9/pull/11310

2020-12-07 21:08 UTC, 0xdaryl requested changes
Minor nits only.

2020-12-07 21:08 UTC, 0xdaryl commented on runtime/compiler/env/RuntimeAssumptionTable.hpp
> +    * and calls the serialize on them. It then also puts the owning metadata for each assumption.
Instead of "the serialize", do you mean "the assumption's serialize() method" ?

2020-12-07 21:08 UTC, 0xdaryl commented on runtime/compiler/env/RuntimeAssumptionTable.hpp
> +    * and calls the serialize on them. It then also puts the owning metadata for each assumption.
> It then also puts the owning metadata for each assumption.

Where does it "put" this?

2020-12-07 21:08 UTC, 0xdaryl commented on runtime/compiler/runtime/ClassUnloadAssumption.cpp
> +     _totalSizeOfAssumptionsToBeSerialized=0;
Fix indentation.

2020-12-07 21:08 UTC, 0xdaryl commented on runtime/compiler/runtime/RuntimeAssumptions.hpp
> +      uint32_t                  _size;
Why so much whitespace before field names?

2020-12-09 23:11 UTC, dsouzai commented on runtime/compiler/env/CHTable.cpp
> +   // TODO: All of this data should be convered into position independent offsets
Opened https://github.com/eclipse/openj9/issues/11427

2020-12-09 23:12 UTC, dsouzai commented
@0xdaryl addressed review comments.

2021-05-17 14:17 UTC, genie-openj9 commented
Can one of the admins verify this patch?

2024-01-23 18:57 UTC, dsouzai commented
Closing this, as the snapshot tech uses CRIU.

2024-01-23 18:57 UTC, closed without merging