WIP: Adding `concurrent-start/end` for Concurrent Global/Marking
eclipse-openj9/openj9 pull request #12247
Opened 2021-03-18 17:29 UTC by gza060625

This is one follow up PR to:
https://github.com/eclipse/omr/pull/5781

Signed-off-by: Enson Guo <enson.guo@ibm.com>

2021-03-18 20:40 UTC, RSalman requested changes

2021-03-18 20:40 UTC, RSalman commented on runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.hpp
> -	virtual const char *getConcurrentTypeString() { return "GMP work packet processing"; }
With this removed, there's a complication on relying on `getCycleType(_stats->concurrentType)` for the concurrent type string. 
`OMR_GC_CYCLE_TYPE_VLHGC_GLOBAL_MARK_PHASE` will result in "global mark phase" (see MM_VerboseHandlerOutputVLHGC::getCycleType)  and according to this original implementation it should be "GMP work packet processing"

2021-03-19 04:13 UTC, RSalman reviewed
LGTM - will approve once dependent changes are finalized/approved

2021-04-22 18:24 UTC, RSalman approved these changes

2021-05-04 19:55 UTC, RSalman commented
@amicic Ready to be merged, OMR changes are in.

2021-05-05 15:13 UTC, amicic commented
This is mutually dependent on/to https://github.com/eclipse/omr/pull/5781 (which is merged, but not promoted), so not make sense even trying to compile. Merging....

2021-05-05 15:15 UTC, merged