[WIP] Disable impdep1 handling for OpenJDK MHs
eclipse-openj9/openj9 pull request #12660
Opened 2021-05-10 17:41 UTC by EricYangIBM

Wrap the impdep1 handler in 'if defined J9VM_OPT_METHOD_HANDLE' as it
is OpenJ9 specific.

Fixes: #12251
Signed-off-by: Eric Yang <eric.yang@ibm.com>

2021-05-10 19:11 UTC, fengxue-IS requested changes
This is a good start Eric, take a look at the actual bytecode `JBimpdep1` that is used to invoke this method call in the VM and change them to map to `JBunimplemented` when `J9VM_OPT_OPENJDK_METHODHANDLE` is enabled.

Also, if the dispatch/call location for this method is ifdefed, then you can wrap the entire method with the ifdef block (similar to [`invokeBasic`](https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/BytecodeInterpreter.hpp#L8294)

2021-05-13 18:58 UTC, EricYangIBM commented
@fengxue-IS Should I wrap `JBimpdep1` in [bcnames.c](https://github.com/eclipse-openj9/openj9/blob/a6bf623d7dcbfcc727980536fb75c206e9dd287d/runtime/oti/bcnames.h#L274) as well? If so I will have to wrap [BytecodeInterpreter.inc](https://github.com/eclipse-openj9/openj9/blob/a6bf623d7dcbfcc727980536fb75c206e9dd287d/runtime/vm/BytecodeInterpreter.inc#L64-L65) as well.

2021-05-13 20:02 UTC, fengxue-IS commented
Do you mean bcnames.h? yes
@babsingh do we need to retain `CFR_BC_impdep1` and  `impdep1PC` for DDR?
These two should not be needed by VM for OpenJDK MH, I am not sure if they are still required to make DDR stackwalker function correctly

2021-05-13 20:19 UTC, babsingh commented
Compatibility with DDR should not be impacted. Otherwise, DDR won't properly read old core files where `impdep1` is used.

@gacholio Can you confirm your preferred approach of disabling `impdep1` for OJDK MHs?

2021-05-17 14:15 UTC, genie-openj9 commented
Can one of the admins verify this patch?

2021-05-17 15:30 UTC, gacholio commented on runtime/oti/bcnames.h
> +#if defined(J9VM_OPT_METHOD_HANDLE)
Please don't do this - the bytecode is part of the specification.

2021-05-17 15:30 UTC, gacholio commented on runtime/oti/cfr.h
> +#if defined(J9VM_OPT_METHOD_HANDLE)
Same here.

2021-05-17 15:31 UTC, gacholio commented on runtime/util/bcnames.c
> +#if defined(J9VM_OPT_METHOD_HANDLE)
And here.

2021-05-17 15:32 UTC, gacholio commented
Rather than tag every location I'll comment here - please do not remove the bytecode itself, just the implementation.

2021-05-17 17:08 UTC, EricYangIBM commented
> Rather than tag every location I'll comment here - please do not remove the bytecode itself, just the implementation.

Done. Removed changes in runtime/util/bcnames.c, runtime/util/jbcmap.c, runtime/util/pcstack.c, runtime/oti/bcnames.h, runtime/oti/cfr.h.

2021-05-17 18:30 UTC, gacholio approved these changes

2021-05-17 18:30 UTC, gacholio commented
Please squash the commites and I'll launch some testing.

2021-05-17 21:00 UTC, EricYangIBM commented
> Please squash the commits and I'll launch some testing.

Commits are squashed.

2021-05-17 21:14 UTC, gacholio commented
jenkins test sanity zlinux jdk8

2021-05-17 21:15 UTC, gacholio commented
Jenkins test sanity xlinuxval jdknext

2021-05-18 04:24 UTC, merged