[WIP] Hide generated frames with hidden annotation
eclipse-openj9/openj9 pull request #12716
Opened 2021-05-18 21:03 UTC by fengxue-IS

- new CFR_METHOD_EXT_HIDDEN_ANNOTATIONS extended modifier
- new macro to check for the new modifier
- map LambdaForm$Hidden / vm.annotation.Hidden to HIDDEN_ANNOTATION
- Update swalk to skip hidden frame by default

Replaces: #12672 
Fixes: #11872, Fixes: #7741

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

2021-05-18 21:04 UTC, fengxue-IS commented
@babsingh can you please take a look

2021-05-19 14:39 UTC, babsingh requested changes
Can you confirm if ...
- no regression is seen in personal builds?
- #11872 and #7741 are fixed?

2021-05-19 14:39 UTC, babsingh commented on runtime/vm/swalk.c
> +	{
Is the extra scope required?

2021-05-20 17:27 UTC, fengxue-IS commented on runtime/vm/swalk.c
> +			UDATA extraModifiers = getExtendedModifiersDataFromROMMethod(romMethod);
fixed

2021-05-20 17:27 UTC, fengxue-IS commented on runtime/bcutil/ClassFileOracle.cpp
> +	{HIDDEN_SIGNATURE, sizeof(HIDDEN_SIGNATURE)},
fixed

2021-05-20 17:28 UTC, fengxue-IS commented on runtime/vm/swalk.c
> +		J9ROMMethod * romMethod = J9_ROM_METHOD_FROM_RAM_METHOD(walkState->method);
fixed

2021-05-28 12:28 UTC, tajila commented
Is this ready for another review @fengxue-IS ?

2021-05-28 16:33 UTC, fengxue-IS commented
> Is this ready for another review @fengxue-IS ?

Yes, can you take a look please

2021-06-01 15:02 UTC, tajila commented
@gacholio Please review these changes

2021-06-01 16:12 UTC, gacholio commented on debugtools/DDR_VM/data/superset-constants.dat
> +C|CFR_METHOD_EXT_HIDDEN_ANNOTATIONS
Is this intentionally changed?

2021-06-01 16:23 UTC, gacholio commented on debugtools/DDR_VM/data/superset-constants.dat
> +C|CFR_METHOD_EXT_HIDDEN_ANNOTATIONS
I thought this file was generated.

2021-06-01 16:28 UTC, gacholio commented
Copyright may need to be updated - the link goes nowhere so it's hard to say.

2021-06-01 17:13 UTC, gacholio commented
This is not the correct way to do this - the stack walker should not be skipping these frames, it should be done inside the frame iterator. There are many cases where we want the true view of the stack.

2021-06-01 17:24 UTC, fengxue-IS commented
> This is not the correct way to do this - the stack walker should not be skipping these frames, it should be done inside the frame iterator. There are many cases where we want the true view of the stack.

@Gac can you give a bit more insight as to which type of iterators should skip these frames (beyond the getCallerClass interators) or which shouldn't?

2021-06-01 17:46 UTC, gacholio commented
Anyone dealing with hidden frames of any kind needs to be updated. Now would be a good time to commonize the code where possible.

Suggest searching for `J9AccMethodFrameIteratorSkip` and `jlrMethodInvoke`.

2021-06-01 17:47 UTC, gacholio commented
Is this not identical to `FrameIteratorSkip`? How does this differ?

2021-06-01 18:15 UTC, fengxue-IS commented
> Is this not identical to `FrameIteratorSkip`? How does this differ?
I am not sure if FrameIteratorSkip and Hidden are the same thing as JIT seems to be using `J9AccMethodFrameIteratorSkip` and ROMClassWriter as well. So I wasn't sure if these can be just mapped to FrameIteratorSkip

2021-06-01 18:20 UTC, gacholio commented
As long as we can recreate the class file from the ROM class with the correct annotations, I can't see any immediate reason we can't re-use the skip tag bit.

2021-06-11 20:08 UTC, fengxue-IS commented
I have updated the code as Gac suggested to reuse the `J9AccMethodFrameIteratorSkip` flag which OpenJ9 MH used for skipping internal methods. ifdefed out the JIT code that checks this flag under OpenJDK MH as it nolonger identify `thunk_archetype` methods

@tajila can you take a look at this

2021-06-18 17:53 UTC, tajila approved these changes

2021-06-18 17:53 UTC, tajila commented
@0xdaryl Please review the JIT changes

2021-06-18 18:28 UTC, 0xdaryl approved these changes

2021-06-18 18:36 UTC, gacholio approved these changes

2021-06-18 18:36 UTC, gacholio commented
jenkins test sanity zlinux jdk8

2021-06-18 18:37 UTC, gacholio commented
jenkins test sanity winojdk292,xlinuxojdk292 jdk16 depends ibmruntimes/openj9-openjdk-jdk16#29

2021-06-18 18:37 UTC, gacholio commented
jenkins test sanity,extended plinux jdk11

2021-06-20 19:01 UTC, merged