Enable getCallerClass optimization for JITServer
eclipse-openj9/openj9 pull request #13172
Opened 2021-07-12 17:55 UTC by dmitry-ten

This commit enables the optimization by adding a new
method `J9::VMMethodEnv::isFrameIteratorSkipMethod` that
checks whether a ROM method has `J9AccMethodFrameIteratorSkip`
flag set.

Closes: #13098

2021-07-12 17:57 UTC, dmitry-ten commented
@dsouzai @fjeremic  could you review this please?

2021-07-12 17:59 UTC, fjeremic approved these changes
Looks reasonable to me. Leaving comitter duties for an expert in the area.

2021-07-12 18:05 UTC, dsouzai requested changes
Requires a couple of changes, one cosmetic, one functional.

2021-07-12 18:05 UTC, dsouzai commented on runtime/compiler/env/J9VMMethodEnv.cpp
> +   return (romMethod->modifiers & J9AccMethodFrameIteratorSkip) == J9AccMethodFrameIteratorSkip;
```suggestion
   return _J9ROMMETHOD_J9MODIFIER_IS_SET(romMethod, J9AccMethodFrameIteratorSkip)
```

2021-07-12 18:05 UTC, dsouzai commented on runtime/compiler/env/VMJ9.cpp
> +            if (TR::Compiler->mtd.isFrameIteratorSkipMethod(callerMethod))
This is wrong, should be:
```suggestion
            if (!TR::Compiler->mtd.isFrameIteratorSkipMethod(callerMethod))
```

2021-07-12 18:15 UTC, dmitry-ten commented
Pushed the changes,

2021-07-12 18:18 UTC, dsouzai approved these changes

2021-07-12 18:19 UTC, dsouzai commented
jenkins test sanity xlinux,xlinuxjit jdk11

2021-07-12 21:41 UTC, mpirvu approved these changes
LGTM

2021-07-14 04:08 UTC, mpirvu commented
Tests have passed, hence merging.

2021-07-14 04:08 UTC, merged