Implement isStable() query for JITServer
eclipse-openj9/openj9 pull request #13203
Opened 2021-07-15 15:01 UTC by dmitry-ten

PR #13178 introduced a new front-end query: `TR_J9VMBase::isStable()`.
This commit adds a JITServer version of this method, which also requires
adding a new message type - `VM_isStable`.

Closes: #12953

2021-07-15 15:02 UTC, dmitry-ten commented
@dsouzai, @mpirvu, could one of you review this?

I checked the impact of the new message type, and there are only ~40-50 extra messages in AcmeAir, so I don't think caching is needed here.

2021-07-15 15:03 UTC, dmitry-ten commented
@gita-omr fyi.

2021-07-16 07:37 UTC, mpirvu reviewed
LGTM. I have a small inline comment and also we need to advance the version number due to the extra message.

2021-07-16 07:37 UTC, mpirvu commented on runtime/compiler/control/JITClientCompilationThread.cpp
> +         if (fieldClass)
Since we don't send a message when fieldClass is NULL we should use an assert here rather than an `if` test

2021-07-16 15:20 UTC, dsouzai requested changes
I don't like the fact that `TR_J9ServerVM::isStable` is basically a copy of `TR_J9VMBase::isStable` except for 
```
- bool isStable = jitIsFieldStable(comp->fej9()->vmThread(), fieldClass, cpIndex);
+ JITServer::ServerStream *stream = _compInfoPT->getMethodBeingCompiled()->_stream;
+ stream->write(JITServer::MessageType::VM_isStable, fieldClass, cpIndex);
+ bool isStable = std::get<0>(stream->read<bool>());
```
It would be better to just refactor out this section for JIT and JITServer, rather than duplicate code to this extent.

2021-07-16 15:24 UTC, dmitry-ten commented
Ok, I'll just create another version of this method with signature `isStable(J9Class *fieldClass, int cpIndex)` and put the differing code there.

2021-07-16 16:32 UTC, dmitry-ten commented
@dsouzai updated.

2021-07-16 16:58 UTC, dsouzai approved these changes

2021-07-16 16:58 UTC, dsouzai commented
jenkins test sanity xlinux,xlinuxjit jdk11

2021-07-17 05:15 UTC, merged