Enable ValueType testing on all platforms
eclipse-openj9/openj9 pull request #13274
Opened 2021-08-04 20:01 UTC by tajila

Enable ValueType testing on all platforms

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

2021-08-04 20:01 UTC, tajila commented
@AdamBrousseau please review these changes

2021-08-04 20:07 UTC, tajila commented
I guess it will use eclipse-openj9/openj9 rather than this PR for PR builds

2021-08-10 13:07 UTC, AdamBrousseau requested changes
Your PR should work once those commas are fixed.

2021-08-10 13:07 UTC, AdamBrousseau commented on buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
> +         'x86-64_windows_aot' : CURRENT_RELEASES
Need a comma `,` at end of this line.

2021-08-10 13:07 UTC, AdamBrousseau commented on buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
> +            'winaot' : ['x86-64_windows_aot']
Need a comma `,` at end of this line.

2021-08-10 13:07 UTC, AdamBrousseau commented on buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
> +         's390x_zos_vt_standard' : ['next'],
I think we only have 11 for z/os at the moment so I'm not sure if these 2 lines are req'd. Won't hurt anything but may not work if you try it.

2021-08-10 13:18 UTC, tajila commented
Jenkins test sanity,extended plinuxval jdknext

2021-08-10 13:23 UTC, tajila commented
Jenkins test sanity,extended zlinuxval jdknext

2021-08-10 13:24 UTC, tajila commented
Jenkins test sanity,extended alinuxval jdknext

2021-08-10 13:24 UTC, tajila commented
Jenkins test sanity plinuxvalst jdknext

2021-08-10 13:24 UTC, tajila commented
Jenkins test sanity zlinuxvalst jdknext

2021-08-10 13:24 UTC, tajila commented
Jenkins test sanity alinuxvalst jdknext

2021-08-10 18:18 UTC, AdamBrousseau approved these changes

2021-08-10 18:21 UTC, AdamBrousseau reviewed
I approved and then noticed the build failures. I'll have to take a more in depth look to see why those errors are there.

2021-08-10 18:31 UTC, tajila commented
I think the s390x failure is intermittent

2021-08-10 18:31 UTC, tajila commented
Jenkins test sanity zlinuxvalst jdknext

2021-08-10 18:33 UTC, tajila commented
Jenkins test sanity aixvalst jdknext

2021-08-10 18:33 UTC, tajila commented
Jenkins test sanity winvalst jdknext

2021-08-10 18:33 UTC, tajila commented
Jenkins test sanity,extended osxval jdknext

2021-08-10 18:33 UTC, tajila commented
Jenkins test sanity,extended aixval jdknext

2021-08-10 18:33 UTC, tajila commented
Jenkins test sanity,extended macval jdknext

2021-08-11 16:03 UTC, AdamBrousseau commented
@tajila I think you just need to rebase your branch.
The aarch spec now builds in docker and should look like this
```
aarch64_linux:
  extends: ['boot_jdk_default', 'debuginfo', 'openjdk_reference_repo', 'openssl']
  boot_jdk:
    arch: 'aarch64'
    os: 'linux'
  release:
    all: 'linux-aarch64-server-release'
    8: 'linux-aarch64-normal-server-release'
    11: 'linux-aarch64-normal-server-release'
  node_labels:
    build: 'ci.role.build && hw.arch.aarch64 && sw.tool.docker'
    docker_image:
      11: 'adoptopenjdk/centos7_build_image@sha256:b2cc072a5c6196461a0993c6817d7540b8c8fcbce40f63cd5bb49eb6d7d61d89'
  build_env:
    vars: 'CC=/usr/local/gcc/bin/gcc-7.5 CXX=/usr/local/gcc/bin/g++-7.5'
```

2021-08-25 13:41 UTC, tajila commented
Jenkins test sanity winvalst jdknext

2021-08-25 13:42 UTC, tajila commented
Jenkins test sanity alinuxvalst jdknext

2021-08-25 13:42 UTC, tajila commented
Jenkins test sanity,extended alinux jdknext

2021-08-25 13:43 UTC, tajila commented
Jenkins test sanity,extended alinuxval jdknext

2021-08-25 13:43 UTC, tajila commented
Jenkins test sanity,extended winval jdknext

2021-09-29 19:53 UTC, tajila commented
Jenkins test sanity,extended alinuxval jdknext

2021-09-29 19:53 UTC, tajila commented
Jenkins test sanity,extended winval jdknext

2021-09-29 19:53 UTC, tajila commented
Jenkins test sanity,extended aixval jdknext

2021-09-29 19:53 UTC, tajila commented
Jenkins test sanity,extended osxval jdknext

2021-09-30 12:21 UTC, tajila commented
We will need to fix some compilation issues on some of the platforms, but looks like the builds work.

2021-09-30 12:21 UTC, tajila commented
@pshipton please review/merge these changes

2021-09-30 14:57 UTC, pshipton approved these changes

2021-09-30 14:57 UTC, merged