[WIP] Simplify wrappedCompile
eclipse-openj9/openj9 pull request #13413
Opened 2021-08-30 14:20 UTC by singh264

Closes: #12496
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com

2021-08-30 14:30 UTC, singh264 commented
@zl-wang @babsingh requesting preliminary feedback

2021-09-01 20:13 UTC, babsingh commented
I am not the correct person to review the JIT changes. @dsouzai Can you please review these changes or assign a JIT reviewer for this PR?

2021-09-17 18:40 UTC, dsouzai requested changes
Overall looks good; you're on the right track. Thanks for picking this up @singh264 :).

2021-09-17 18:40 UTC, dsouzai commented on runtime/compiler/control/CompilationThread.cpp
> +TR::CompilationInfoPerThreadBase::setCompiledMethodOptimzationPlan(TR::CompilationInfoPerThreadBase *compilationInfo, TR_ResolvedMethod *compilee, TR_J9VMBase *vm)
I think this is incorrectly named, it should be something along the lines of `addUpgradeHintInSCCIfNeeded`.

2021-09-17 18:40 UTC, dsouzai commented on runtime/compiler/control/CompilationThread.cpp
> +TR::CompilationInfoPerThreadBase::isCompilingRestrictedMethod(TR::CompilationInfoPerThreadBase *compilationInfo, TR_ResolvedMethod *compilee, CompileParameters *compileParameters, TR_FilterBST *&filt
I think just calling this `isRestrictedMethod` is sufficient.

2021-09-17 18:40 UTC, dsouzai commented on runtime/compiler/control/CompilationThread.cpp
> +      if (compilationInfo->_methodBeingCompiled->isOutOfProcessCompReq() || compilationInfo->methodCanBeCompiled(compileParameters->trMemory(), vm, compilee, filterInfo))
Better to split these into two lines.

2021-09-17 18:40 UTC, dsouzai commented on runtime/compiler/control/CompilationThread.cpp
> +            return false;
Formatting.

2021-09-17 18:40 UTC, dsouzai commented on runtime/compiler/control/CompilationThread.cpp
> +            return false;
Formatting.

2021-09-17 18:40 UTC, dsouzai commented on runtime/compiler/control/CompilationThread.cpp
> +TR::CompilationInfoPerThreadBase::isCompilingWithExcessiveCacheSize(TR::CompilationInfoPerThreadBase *compilationInfo, CompileParameters *compileParameters)
A better name might be `isCodeOrDataCacheFull`.

2021-09-17 18:40 UTC, dsouzai commented on runtime/compiler/control/CompilationThread.cpp
> +      if (isCompilingRestrictedMethod(compilationInfo, compilee, compileParameters, filterInfo) || isCompilingWithExcessiveCacheSize(compilationInfo, compileParameters))
Better to split this into two lines.

2021-10-15 20:57 UTC, singh264 commented
`method_name line_start - line_end`

createCompilee [8436 - 8469](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L8436-L8469)
addUpgradeHintInSCCIfNeeded [8419 - 8434](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L8419-L8434)
isRestrictedMethod [8392 - 8417](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L8392-L8417)
isCodeOrDataCacheFull [8365 - 8390](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L8365-L8390)
isOutOfProcessCompReq [8356 - 8363](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L8356-L8363)
processOutOfProcessComp [8332 - 8354](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L8332-L8354)
processNonOutOfProcessComp [8227 - 8330](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L8227-L8330)
aotCompilationReUpgradedToWarm [7870 - 7897](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L7870-L7897)
adjustOptionsForAotCompilation [7840 - 7868](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L7840-L7868)
tweakAotLoadCompilationStrategy [8030 - 8225](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L8030-L8225)
processSamplingJProfiling [7899 - 8028](https://github.com/singh264/openj9/blob/refactor_wrappedcompile_oct15/runtime/compiler/control/CompilationThread.cpp#L7899-L8028)

2021-10-29 19:18 UTC, singh264 commented
I think https://github.com/singh264/openj9/pull/2 is an extension of the changes in this pull request.

2022-01-10 22:37 UTC, ymanton commented
This PR has merge conflicts. Please fix those before requesting a review.

2022-01-11 22:19 UTC, closed without merging