Convert criu files to cpp
eclipse-openj9/openj9 pull request #13834
Opened 2021-10-29 18:52 UTC by tajila

Convert criu files to cpp

Also fix some build config issues

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

2021-10-29 18:55 UTC, tajila commented
Jenkins test sanity win jdk8,jdk11

2021-11-01 21:01 UTC, keithc-ca requested changes

2021-11-02 19:18 UTC, keithc-ca commented
PR builds don't enable CRIU; ​https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/1083/ demonstrates this doesn't break builds without CRIU (and nothing that should affect that outcome has since changed). A local build with CRIU enabled passed.

2021-11-02 19:18 UTC, keithc-ca approved these changes

2021-11-02 19:18 UTC, merged