Add zNext hardware exploitation to JIT z/codegen
eclipse-openj9/openj9 pull request #14179
Opened 2021-12-17 19:14 UTC by dchopra001

2021-12-17 19:27 UTC, dchopra001 commented
Tagging @joransiu @r30shah @VermaSh for review. If you could please make sure I've brought over all your changes correctly that would be great! Thanks!

2021-12-17 21:17 UTC, VermaSh commented
`test/functional/JIT_Test/testng.xml` change [1] is missing from this PR. Do we not need to add the new test suite, `TestJavaIntegerAndLongToString.java`?

[1] https://github.ibm.com/runtimes/openj9/compare/ibm_sdk...zartemis "Internal Diff"

2021-12-17 21:24 UTC, dchopra001 commented
> test/functional/JIT_Test/testng.xml change [1] is missing from this PR. Do we not need to add the new test suite, TestJavaIntegerAndLongToString.java?

I must have missed this change during a rebase. I've added it back here now. Good catch!

2021-12-19 23:02 UTC, VermaSh requested changes

2022-01-10 14:59 UTC, dchopra001 commented on runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
> +
Yeah, I would say so. The rest of this file is also formatted in the same way to differentiate between each class' methods that we recognize.

2022-01-10 16:54 UTC, VermaSh commented
Looks good, thanks for making the changes @dchopra001!

2022-01-10 18:17 UTC, r30shah approved these changes
LGTM, seems like one of the files needed copyrights updated.

2022-01-10 20:19 UTC, VermaSh approved these changes

2022-01-13 21:44 UTC, joransiu commented
For the copyright check, I think we need to update the year for all the files modified with 2022.

2022-01-13 21:50 UTC, joransiu commented
jenkins test zlinux jdk8,jdk11,jdk17 depends https://github.com/eclipse/omr/pull/6276

2022-01-14 02:36 UTC, joransiu commented
jenkins test sanity zlinux jdk8,jdk11 depends eclipse/omr#6276

2022-01-17 14:42 UTC, dchopra001 commented
The tests passed and I've now updated the copyright info. Once we have the OMR PR merged, we should be able to merge this as well.

2022-01-17 15:40 UTC, joransiu approved these changes

2022-01-20 20:23 UTC, 0xdaryl commented
Dependent upstream PR has merged.  It needs to pass the acceptance build before this PR can merge.

2022-01-23 13:26 UTC, joransiu commented
jenkins test sanity zlinux jdk8

2022-01-23 17:34 UTC, merged