Refactor the method named wrappedcompile
eclipse-openj9/openj9 pull request #14252
Opened 2022-01-11 22:43 UTC by singh264

Closes: https://github.com/eclipse-openj9/openj9/issues/12496.
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com.

2022-01-11 23:25 UTC, singh264 commented on runtime/compiler/control/CompilationThread.cpp
> +         compiler = compiler_tmp;
I think the temporary variable `compiler_tmp` is a workaround to the following error during the `make all` step of the build process: `error: binding reference of type ‘TR::Compilation*&’ to ‘TR::Compilation* volatile’ discards qualifiers`.

2022-01-11 23:53 UTC, singh264 commented
I think the pull request combines the code changes in https://github.com/eclipse-openj9/openj9/pull/13413 and https://github.com/singh264/openj9/pull/2.

2022-01-17 23:36 UTC, singh264 commented
I think the Jenkins test results of the code changes in the GitHub pull request is located at the following url: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/11543/.

2022-02-22 03:47 UTC, ymanton requested changes
On first glance, looks promising. I'll take another pass shortly.

2022-02-22 19:10 UTC, ymanton requested changes
Some code appears to be missing in the current set of patches.

Also, most (all?) of the functions have their bodies indented too far. Can you change it so that it looks like
```
class:function()
   {
   // body indented at same level as function braces
   }
```

2022-03-07 15:59 UTC, singh264 commented
I think the requested code changes are added to the GitHub pull request.

2022-03-09 05:15 UTC, ymanton requested changes
Apologies for the delay, it takes me a while to read through each revision of this PR.

I found some code that's been committed recently that was lost in your patches, but it looks close to the finish line. Thanks for your effort.

2022-03-09 05:15 UTC, ymanton commented on runtime/compiler/control/CompilationThread.cpp
> +#if defined(J9VM_OPT_JITSERVER)
Looks like some new code is here in the current version:

```
            // Under -Xtune:throughput, increase the scratch space limit for hot/scorching compilations
            else if (TR::Options::getAggressivityLevel() ==  TR::Options::TR_AggresivenessLevel::AGGRESSIVE_THROUGHPUT &&
                     compiler->getOptions()->getOptLevel() > warm &&
                     TR::Options::getScratchSpaceLimitForHotCompilations() > proposedScratchMemoryLimit) // Make sure we don't decrease the value proposed so far
               {
               proposedScratchMemoryLimit = TR::Options::getScratchSpaceLimitForHotCompilations();
               }
```

Please update.

2022-03-09 05:18 UTC, ymanton commented
FYI @mpirvu this PR provides a much needed cleanup of `wrappedCompile()`. Thought you should know since you've made changes here recently.

2022-03-09 12:32 UTC, mpirvu commented
Thanks for letting me know. We need to do a lot of testing for this PR (functional and performance) because, from past experience, it's very easy to introduce a subtle bug during refactoring big pieces of code.

2022-03-14 12:45 UTC, singh264 commented
I think the local test results of the code changes in the GitHub pull request is located at the following url: https://drive.google.com/file/d/1GorcTSF7XLxhSLpYcEJdGfLYgNPnw4eh/view?usp=sharing.

I think the local test results of the code changes in the GitHub pull request could be displayed with the file that is located at the following url: https://github.com/singh264/scripts/blob/main/display_test_openj9-openjdk-jdk8_results.sh.

2022-03-14 12:46 UTC, singh264 commented
I think the requested code changes are added to the GitHub pull request.

2022-03-18 17:16 UTC, ymanton commented
I've taken a first pass at this and it looks good to me, however

> I think the local test results of the code changes in the GitHub pull request is located at the following url: https://drive.google.com/file/d/1GorcTSF7XLxhSLpYcEJdGfLYgNPnw4eh/view?usp=sharing.

this output is showing a crash with `wrappedCompile()` near the top of the call stack. Is this something you've looked into?

2022-03-24 16:41 UTC, singh264 commented
What would be the next step to look into the method named wrappedCompile() that could not complete near the top of the call stack?

2022-03-24 16:42 UTC, singh264 commented
What would be the next step to look into the method named wrappedCompile() that could not complete near the top of the call stack?

2022-03-24 16:43 UTC, singh264 commented
What would be the next step to look into the method named wrappedCompile() that could not complete near the top of the call stack?

2022-03-24 16:49 UTC, singh264 commented
What would be the next step to look into the method named wrappedCompile() that could not complete near the top of the call stack?

2022-03-24 18:33 UTC, ymanton commented
I built your changes and ran `jdk/bin/java -Xjit:count=0 -version`[^1] and it crashed. I then unzipped the debug symbols for the JIT library[^2] and opened the core file in gdb[^3]. I then looked at the backtrace, which looks as follows:

```
(gdb) where
#0  __pthread_kill (threadid=<optimized out>, signo=11) at ../sysdeps/unix/sysv/linux/pthread_kill.c:56
#1  0x00007fdcc336017d in omrdump_create ()
   from jdk/jre/lib/amd64/default/libj9prt29.so
...
#11 0x00007fdcc336110a in mainSynchSignalHandler ()
   from jdk/jre/lib/amd64/default/libj9prt29.so
#12 <signal handler called>
#13 J9::Compilation::fej9 (this=0x0)
    at openj9/runtime/compiler/compile/J9Compilation.cpp:251
#14 0x00007fdcc24d8864 in TR::CompilationInfoPerThreadBase::wrappedCompile (portLib=<optimized out>, opaqueParameters=<optimized out>)
    at openj9/runtime/compiler/control/CompilationThread.cpp:9268
...
#25 0x00007fdcc390c163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

OpenJ9 has a signal handler that will trap segfaults and do some extra processing before dumping the core. This can be seen in frames 0-12 so we can ignore them, they're not relevant to the cause of the crash. Frames 13 and 14 tell us what we need to know:

```
#13 J9::Compilation::fej9 (this=0x0)
    at openj9/runtime/compiler/compile/J9Compilation.cpp:251
#14 0x00007fdcc24d8864 in TR::CompilationInfoPerThreadBase::wrappedCompile (portLib=<optimized out>, opaqueParameters=<optimized out>)
    at openj9/runtime/compiler/control/CompilationThread.cpp:9268
```

```
││   9266           try                                                                                                                                     
││   9267              {                                                                                                                                    
││  >9268              TR_J9VMBase *fej9 = (TR_J9VMBase *)(compiler->fej9());                                                                               
││   9269              TR_CatchBlockProfileInfo * profileInfo = TR_CatchBlockProfileInfo::get(compiler);                                                    ││   9270              storeHintsInTheSCC(compilationInfo, vm, fej9, metaData, profileInfo, scratchSegmentProvider);                                        ││   9271              }
```

You're calling `compiler->fej9()` (frame 14) but inside `fej9()` the `this` object is NULL (frame 13), which means that `compiler` was NULL. Consider how the code was originally written:

https://github.com/eclipse-openj9/openj9/blob/cc41409c304bf666dabb98e51eedbb1042966dcb/runtime/compiler/control/CompilationThread.cpp#L9078-L9086

The original code was checking if `metaData` was non-NULL before calling `fej9()` however in your code you've moved that check into `storeHintsInTheSCC()`. If `compiler` is NULL `metaData` will also be NULL, so you need to check that before attempting to call `fej9()`. I suggest passing `compiler` into `storeHintsInTheSCC()` and calling `fej9()` after you've checked if `metaData` is non-NULL. Also, you have `profileInfo = TR_CatchBlockProfileInfo::get(compiler)` being done before the check, and the same line inside `storeHintsInTheSCC()` except it's commented out. I suggest you uncomment it, delete line 9269, and stop passing `profileInfo` into `storeHintsInTheSCC()` because as it currently is it will likely also crash if/when `compiler` is NULL.

[^1]: I used `count=0` to force the compiler to compile as many methods as possible in order to exercise your changes. You can use it as a quick test of your changes prior to running one of the test buckets.
[^2]: `$ cd jdk/jre/lib/amd64/default && unzip libj9jit29.diz -> libj9jit29.debuginfo` By default debug symbols are zipped during the build process unless you change that when you invoke `configure`.
[^3]: `$ gdb jdk/bin/java core.20220324.105000.2367989.0001.dmp`

2022-03-24 18:45 UTC, ymanton requested changes

2022-03-24 18:45 UTC, ymanton commented on runtime/compiler/control/CompilationThread.cpp
> +         // TR_CatchBlockProfileInfo * profileInfo = TR_CatchBlockProfileInfo::get(compiler);
Let's restore this line and delete the parameter with the same name.

2022-03-24 18:45 UTC, ymanton commented on runtime/compiler/control/CompilationThread.cpp
> +      storeHintsInTheSCC(compilationInfo, vm, fej9, metaData, profileInfo, scratchSegmentProvider);
`compiler` may be NULL so we need to avoid executing the first two statements unconditionally.

2023-01-06 14:15 UTC, singh264 commented
I think the local test results of the code changes in the GitHub pull request is located at the following url: https://drive.google.com/file/d/1g6BbwL7bC7k8CpZEFqNxJr9DZK_h3Yem/view?usp=sharing.

I think the local test results of the code changes in the GitHub pull request could be displayed with the file that is located at the following url: https://github.com/singh264/scripts/blob/main/display_test_openj9-openjdk-jdk8_results.sh.

2023-01-06 14:15 UTC, singh264 commented
I think the requested code changes are added to the GitHub pull request.

2023-01-14 23:47 UTC, ymanton commented
Thanks for updating this PR, I'll take a look shortly.

2025-05-30 16:42 UTC, ymanton commented
Hi @singh264, you're welcome to address this or any other refactoring task if you wish. If you decide to pursue this I suggest doing it incrementally and opening much smaller PRs to make it easier to review and merge.

You're also welcome to close this PR if you no longer feel compelled to pursue it.

2025-05-30 21:29 UTC, singh264 commented
It will be pursed by me as I intend to open a PR everytime I shorten the long function.

2025-05-30 22:14 UTC, closed without merging