Disable AOT compilation when SCC is read only
eclipse-openj9/openj9 pull request #14751
Opened 2022-03-20 23:03 UTC by knn-k

This commit adds a check for disabling AOT compilation when SCC is
read only.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

2022-03-20 23:04 UTC, knn-k commented
jenkins test sanity all jdk11

2022-03-21 02:17 UTC, knn-k commented
jenkins test sanity amac jdk11

2022-03-21 12:39 UTC, 0xdaryl commented
@mpirvu : would you mind reviewing this one please?

2022-03-21 14:06 UTC, dsouzai requested changes
Might be better to just reuse the existing code slightly above, ie:

```
+     if (javaVM->sharedClassConfig->runtimeFlags & J9SHR_RUNTIMEFLAG_ENABLE_READONLY)
+        TR::Options::getAOTCmdLineOptions()->setOption(TR_NoStoreAOT);
+
      if (TR::Options::getAOTCmdLineOptions()->getOption(TR_NoStoreAOT))
         {
         javaVM->sharedClassConfig->runtimeFlags &= ~J9SHR_RUNTIMEFLAG_ENABLE_AOT;
         TR_J9SharedCache::setSharedCacheDisabledReason(TR_J9SharedCache::AOT_DISABLED);
```

2022-03-21 22:40 UTC, knn-k commented
I thought I didn't want to unset the `J9SHR_RUNTIMEFLAG_ENABLE_AOT` flag in this case.  You can load AOT code from the SCC while you cannot write to it when the SCC is read only.
In addition, the error messages for the `J9VM_OPT_JITSERVER` case don't seem to apply to the read-only SCC case.

2022-03-22 00:51 UTC, mpirvu commented
I tested and AOT loads happen even when -Xaot:nostore option is provided. This option resets `J9SHR_RUNTIMEFLAG_ENABLE_AOT` flag, so it appears that this does not prevent AOT loads from happening.

However, we don't want that message from JITServer to be emitted, so I am ok with the current implementation.

2022-03-22 00:51 UTC, mpirvu approved these changes

2022-03-22 14:22 UTC, mpirvu commented
@dsouzai if you agree with the discussions above, could you please approve this PR? Thanks

2022-03-22 14:37 UTC, dsouzai approved these changes
Yeah the discussion sounds fine to me. I only mentioned it because when do the AOT validation above, we set `TR_NoStore` and let the subsequent code do what it needs to.

2022-03-22 14:38 UTC, merged