JITServer custom metrics exporter for Prometheus
eclipse-openj9/openj9 pull request #14762
Opened 2022-03-21 23:44 UTC by mpirvu

This commit implements a simple HTTP server, called MetricsServer, that
responds to "GET /metrics" requests from an agent like Prometheus.
The response includes values for all the metrics that JITServer
is willing to provide information on. This commit implements support
for four metrics:
1. CPU utilization of JITServer
2. Physical memory available to JITServer
3. Number of clients connected to JITServer
4. Number of active compilation threads in JITServer

Example of a recognized HTTP request:
```
   GET /metrics HTTP/1.1
   Host: 127.0.0.1:9403
   User-Agent: Prometheus/2.31.1
   Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
   Accept-Encoding: gzip
   X-Prometheus-Scrape-Timeout-Seconds: 3
 ```
Example of a response sent back:
```
   # HELP cpu_utilization Cpu utilization of the JITServer
   # TYPE cpu_utilization gauge
   cpu_utilization 12.000000
   # HELP available_memory Available memory for JITServer
   # TYPE available_memory gauge
   available_memory 32036204544.000000
   # HELP connected_clients Number of connected clients
   # TYPE connected_clients gauge
   connected_clients 1.000000
   # HELP active_threads Number of active compilation threads
   # TYPE active_threads gauge
   active_threads 1.000000
```
The response is in OpenMetrics format (https://openmetrics.io/) so that
other monitoring agents, beyond Prometheus, can collect metrics.

The MetricsServer implemented in this commit runs on a single, dedicated
thread. This limits the interference that the MetricsServer can have on the
rest of JITServer. Up to 4 concurrent HTTP requests can be processed
concurrently, through the use of the "poll" mechanism.
At the moment, the communication with the MetricsServer is not encrypted.
Encryption support will arrive in a future commit.

The MetricsServer functionality is disabled by default.
Command line options:
`-XX:+JITServerMetrics`           enables JITServer MetricsServer
`-XX:-JITServerMetrics`            disables JITServer MetricsServer
`-XX:JITServerMetricsPort=<NNN>`   specifies port number for MetricsServer (default 38500)

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

2022-03-22 00:31 UTC, mpirvu commented
@dsouzai @ymanton could you please review this JITServer PR? Thanks

2022-03-22 15:31 UTC, ymanton reviewed
Looks good to me on first pass.

The code that reads and handles data from sockets >=1 checks if we're handling a new request or continuing to read a previous request, but most of the code looks the same between two cases. Is it possible to refactor it to reduce duplication?

2022-03-23 21:04 UTC, dsouzai requested changes
Overall functionally lgtm, just requesting some changes in terms cleaning up the code a bit.

2022-03-23 21:04 UTC, dsouzai commented on runtime/compiler/runtime/MetricsServer.cpp
> +}
Formatting.

2022-03-23 22:31 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +                        _incompleteRequests[i-1] = new (PERSISTENT_NEW) HttpGetRequest(httpReq);
Assert was forgotten. I'll add it.

2022-03-23 22:33 UTC, mpirvu commented on runtime/compiler/control/HookedByTheJit.cpp
> +      metricsServer->startMetricsThread(javaVM);
There is already a message coming out (in `serveMetricsRequests`) once we managed to open the port:
```
#JITServer: MetricsServer waiting for http requests on port 9404
```

2022-03-23 22:36 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +   setValue(compInfo->getClientSessionHT()->size()); // TODO: do we need a lock?
I added a comment saying that, while to be accurate we need to acquire a lock, accuracy is not very important here.

2022-03-23 23:04 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +         // Note that if we enable keep-alive, then we should not consider this as a timeout
Yes, we set `SO_KEEPALIVE` only for the socket that is listening to new connection requests. All the other sockets do not have `SO_KEEPALIVE`

2022-03-24 02:01 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +      for (nfds_t i = 0; i < 1 + MAX_CONCURRENT_REQUESTS && numSocketsChecked < numSocketsWithData; i++)
Done

2022-03-24 02:01 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +                     if (err == HttpGetRequest::FULL_REQUEST_RECEIVED)
Done

2022-03-24 02:01 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +}
Fixed

2022-03-24 02:01 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +   memcpy(_httpVersion, _buf+pos+5, protocolLength-5);
Addressed

2022-03-24 02:02 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +   if (protocolLength < 6 || protocolLength > 8)
Done

2022-03-24 02:02 UTC, mpirvu commented on runtime/compiler/runtime/MetricsServer.cpp
> +   size_t pathLength = strcspn(_buf + pos, " \r\n");
Done

2022-03-24 02:03 UTC, mpirvu commented
Addressed all review comments. Thanks

2022-03-24 15:49 UTC, dsouzai approved these changes
Code is much cleaner and easier to read now. Thanks!

LGTM.

2022-03-24 18:43 UTC, mpirvu commented
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk17

2022-03-25 02:07 UTC, ymanton approved these changes
LGTM.

2022-03-25 02:15 UTC, mpirvu commented
Some tests failed on x86, but not because of this PR:
```
cmdLineTester_GCCheck_0
cmdLineTester_GCCheck_2
cmdLineTester_GCCheck_3
cmdLineTester_pltest_0
```
All of the above are known to fail on machines were the coredump is moved by the apport service and the test cannot find it.

2022-03-25 02:17 UTC, ymanton commented
Agreed. Merging.

2022-03-25 02:17 UTC, merged