Always call classMatchesCachedVersion in rememberClass
eclipse-openj9/openj9 pull request #15037
Opened 2022-05-10 20:58 UTC by dsouzai

See https://github.com/eclipse-openj9/openj9/issues/15013 for more
details.

It is possible for two J9Classes to have the same J9ROMClass but have
different class chains. However, because a class chain is stored into
the SCC using a key derived from the J9ROMClass, it isn't possible to
store different class chains that have the same first J9ROMClass in the
chain. This can lead to undefined behaviour as invalid AOT code can be
executed.

This PR fixes the issue by changing the code that assumes that if it
can find an existing class chain in the SCC for a given J9Class, that it
is valid for said J9Class. The code now always validates the class
chain.

Closes https://github.com/eclipse-openj9/openj9/issues/15013

2022-05-10 20:58 UTC, dsouzai commented
@mstoodle could you please review/merge?

@JamesKingdon fyi

2022-05-10 22:08 UTC, mstoodle requested changes

2022-05-10 22:08 UTC, mstoodle commented on runtime/compiler/env/J9SharedCache.cpp
> +         LOG(1, "\tchain exists (%p) so nothing to store\n", chainData);
These messages feel a bit cryptic to me.

In the matching case, I suggest:
   class and class chain found are identical so rememberClass returns the class chain

In the failing case, I suggest:
   chain found does not match current class, cannot use class chain so rememberClass returns NULL

2022-05-10 23:28 UTC, mpirvu reviewed
LGTM
Initially, I had some doubts about the ClassChainValidationCaching used in `classMatchesCachedVersion()`, but I think we are ok. I was afraid that we could call classMatchesCachedVersion() with a <j9class, existingClassChain> pair, store `CCVResult::success` in the cache, then later on call again classMatchesCachedVersion() with <j9class, anotherExistingClassChain> and use the cache to draw the wrong conclusion.
However, I think we are safe because for a ROMClass there could only be one existingClassChain, so the scenario with 'anotherExistingClassChain" cannot happen.

2022-05-11 13:54 UTC, dsouzai commented
@mstoodle made requested changes; reworded it slightly to be more consistent with each other.

2022-05-11 13:56 UTC, mpirvu approved these changes

2022-05-11 13:57 UTC, mpirvu commented
jenkins test sanity all jdk17

2022-05-11 14:16 UTC, mstoodle approved these changes
Thanks, @dsouzai

2022-05-12 00:01 UTC, merged