Refactor CRIUConfigurator
eclipse-openj9/openj9 pull request #15047
Opened 2022-05-11 21:03 UTC by tajila

Refactor CRIUConfigurator

Move CRIUConfigurator to a new package that is only exported to
openj9.criu

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

2022-05-11 21:07 UTC, tajila commented
Jenkins compile xlinuxcriu jdk11

2022-05-11 21:24 UTC, keithc-ca requested changes

2022-05-11 21:24 UTC, keithc-ca commented on jcl/src/java.base/share/classes/openj9/internal/criu/security/CRIUConfigurator.java
> +    /** Tracing for CRIUSEC. */
Please indent with tabs for consistency with this repo.

2022-05-11 21:24 UTC, keithc-ca commented on jcl/src/java.base/share/classes/module-info.java.extra
> +exports openj9.internal.security to
This export doesn't match any package; I think you meant to export `openj9.internal.criu.security`.

2022-05-11 21:52 UTC, keithc-ca commented on jcl/src/java.base/share/classes/openj9/internal/criu/security/CRIUConfigurator.java
> +		// which is called before this method.
Please merge these comment lines.

2022-05-11 22:10 UTC, tajila commented
I've addressed the compilation and indentation issues

2022-05-12 15:57 UTC, keithc-ca approved these changes

2022-05-12 15:58 UTC, keithc-ca commented
jenkins compile osx,xlinuxcriu jdk11

2022-05-12 16:01 UTC, keithc-ca commented
jenkins compile xlinuxcriu jdk11 depends ibmruntimes/openj9-openjdk-jdk11#523

2022-05-12 17:30 UTC, keithc-ca commented
For the record, both builds were successful:
* https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/2109
* https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/2110

2022-05-12 17:33 UTC, merged