Remove deprecated MXBean APIs in Java 19 and 20
eclipse-openj9/openj9 pull request #15127
Opened 2022-05-26 18:25 UTC by pshipton

2022-05-26 18:33 UTC, pshipton commented
jenkins compile win jdknext

2022-05-26 18:33 UTC, pshipton commented
jenkins test sanity,extended amac jdknext

2022-05-26 18:53 UTC, pshipton commented
https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/2172/

2022-05-26 18:54 UTC, pshipton commented
jenkins test sanity,extended amac jdknext

2022-05-26 19:10 UTC, pshipton commented
jenkins compile win jdknext

2022-05-26 19:34 UTC, pshipton commented
https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/2175/

2022-05-26 19:39 UTC, pshipton commented
Testing via grinders:
8: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/822
19: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/823

2022-05-27 15:58 UTC, keithc-ca requested changes

2022-05-27 15:58 UTC, keithc-ca commented on runtime/jcl/uma/se6_vm-side_natives_exports.xml
> +	</export>
This is not legal XML: the `<export ... />` element should end with `>`:
```
	<export name="Java_com_ibm_lang_management_internal_ExtendedRuntimeMXBeanImpl_getProcessIDImpl">
		<exclude-if condition="spec.java19" />
	</export>
```

2022-05-27 15:58 UTC, keithc-ca commented on jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedMemoryMXBeanImpl.java
>  	 * Deprecated. Use getTotalPhysicalMemorySize().
This should be updated to advise use of something that isn't going away in Java 20.

2022-05-27 17:42 UTC, pshipton commented
Updated to address comments.

2022-05-27 17:53 UTC, pshipton commented
Tweaked some other javadoc.

2022-05-27 18:38 UTC, keithc-ca approved these changes

2022-05-27 18:54 UTC, keithc-ca commented
I'm satisfied that the recent changes don't invalidate the successful build at https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/2175/; I also did a local build to confirm the UMA changes are good.

2022-05-27 18:55 UTC, merged