Attach API removes world permissions
eclipse-openj9/openj9 pull request #15470
Opened 2022-06-30 21:10 UTC by JasonFengJ9

Attach API removes world permissions

Internal personal builds:
Java 8/11 `x86-64_linux` `sanity.functional` & `extended.functional` - `view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/13441/`
IBM Java 8 - `build_info.php?build_id=31582`

This addresses the concern raised at https://github.com/eclipse-openj9/openj9/issues/15459 - _/tmp/.com_ibm_tools_attach create files with world writeable files._

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

2022-07-05 20:38 UTC, pshipton requested changes
We can't accept this change because it generally breaks attach API notification. The following is my understanding of how notification works:
- lock the notification file of every JVM
- signal the global semaphore once for every JVM running
- each JVM is waiting on the global semaphore and wakes when notified
- after being notified each JVM waits on it's notification file to avoid consuming multiple signals from the global semaphore

If there are any JVMs running which are owned by another user/group, they can consume multiple signals to the global semaphore and cause the JVM being attached to miss a notification. A JVM can consume multiple signals when it's notification file is not locked before the global semaphore is signalled. Based on previous discussion, the JVM notification file for a different user/group cannot be locked without global write permission.

2022-07-05 21:45 UTC, JasonFengJ9 commented
> If there are any JVMs running which are owned by another user/group, they can consume multiple signals to the global semaphore and cause the JVM being attached to miss a notification. 

After one user creates the global semaphore. only same user (and `root`/`administrator`) can consume that global semaphore, i.e., other normal user/group can't access/lock the semaphore hence no further notification, I expect they have no impact on the JVMs launched by the initial user.
This matches the doc "_A process using the Java Attach API must be owned by the same UNIX user ID as the target process._" [1] except that `root` can attach a process owned by a normal user.

[1] https://www.eclipse.org/openj9/docs/attachapi/

2022-07-05 21:50 UTC, pshipton commented
That doesn't make sense to me. It means that only one user/group can use the attach API on a machine. The global semaphore is created with world rw permissons (666).

2022-07-05 21:52 UTC, pshipton commented
`"A process using the Java Attach API must be owned by the same UNIX user ID as the target process."` is a restriction we've imposed for security, and describes when attaches can occur. It doesn't describe how attach api notifications work.

2022-07-05 21:55 UTC, pshipton commented
I think the problem could be fixed by using a sysv message queue for notifications rather than a semaphore.

2022-07-05 21:57 UTC, JasonFengJ9 commented
> It means that only one user/group can use the attach API on a machine. 

This seems the case of OpenJ9 tests and the customer issues I am aware.

> The global semaphore is created with world rw permissons (666).

It appears to me this permission is not necessary, or required w/ the restriction imposed.

2022-07-05 21:58 UTC, JasonFengJ9 commented
> a sysv message queue for notifications rather than a semaphore

It might not be straightforward considering the platforms supported by OpenJ9 Attach API.

2022-07-05 22:03 UTC, pshipton commented
> You are going to have to prove it already doesn't work by creating two separate users on a machine and showing that attach api can only be used by one of them.

Or alternatively, it does work and removing the world write permissions from the files and the global semaphore doesn't break it.

2022-07-05 22:05 UTC, JasonFengJ9 commented
> You are going to have to prove it already doesn't work by creating two separate users on a machine and showing that attach api can only be used by one of them.

I saw this in Linux, `jcmd` launched by one user can't see the jvm launched by another user which is a different normal user w/ existing JDK8.

2022-07-05 22:06 UTC, pshipton commented
> It appears to me this permission is not necessary, or required w/ the restriction imposed.

I think you are misunderstanding the restriction. The restriction doesn't say that attach api can only be used by the first user to try and use it on a machine. Attach api should be usable by all JVMs and users. Just that a user can only connect to their own JVMs, and not JVMs from other users.

2022-07-05 22:08 UTC, pshipton commented
> I saw this in Linux, jcmd launched by one user can't see the jvm launched by another user which is a different normal user w/ existing JDK8.

Yes, this is by design, and is unrelated to the notification implementation.

2022-07-05 22:08 UTC, JasonFengJ9 commented
> Just that a user can only connect to their own JVMs, and not JVMs from other users.

A normal user shouldn't attach to another different user unless they are in same group or the attacher is a `root`.

2022-07-05 22:16 UTC, JasonFengJ9 commented
Just to clarify the scenario:
User A launched JVM 1, JVM 2
User B launched JVM 3, JVM 4
Is the concern about JVM1 can't attach to JVM2 (might be intermittently) assuming User A launched first?

2022-07-05 22:21 UTC, pshipton commented
1 & 2 should be able to attach, and 3 & 4 should also be able to attach.

2022-07-05 22:44 UTC, JasonFengJ9 commented
> They all use a sysv semaphore

Does zOS support same?

2022-07-06 02:13 UTC, pshipton commented
> Does zOS support same?

Yes.

2022-07-06 02:14 UTC, pshipton commented
I assume that without this PR both 1 & 2, 3 & 4 can attach?
I wonder what `-Dcom.ibm.tools.attach.directory` does to make it work? Is a different "global" semaphore created for each different attach.directory?

2022-07-06 02:15 UTC, pshipton commented
I guess changing COMMON_DIRECTORY_PERMISSIONS means other users can't create sub-directories without the world writable set.

2022-07-06 02:21 UTC, JasonFengJ9 commented
> I guess changing COMMON_DIRECTORY_PERMISSIONS means other users can't create sub-directories without the world writable set.

Running a personal build to keep COMMON_DIRECTORY_PERMISSIONS w/ world permission which I assume safe.

2022-07-06 02:40 UTC, JasonFengJ9 commented
> User A launched JVM 1, JVM 2
User B launched JVM 3, JVM 4

With `COMMON_DIRECTORY_PERMISSIONS` world write permission, JVM 1 & 2 can attach each other, and same for JVM 3 & 4.
Updated the PR.

2022-07-06 02:56 UTC, pshipton commented
The problem is that I think you are getting lucky. From my reading of the code 3 & 4 could eat a signal that is meant for 1 or 2 (without the world writable). I suspect the more JVMs you have created by B, the less often attaching between 1 & 2 will work, but I don't know what determines the order of which JVMs get woken first when the global semaphore is signalled. If 1 & 2 happen to get woken before the other JVMs eat the signals, then it will work. Without the world writable the mechanism is broken.

2022-07-06 12:34 UTC, JasonFengJ9 commented
>From my reading of the code 3 & 4 could eat a signal that is meant for 1 or 2 (without the world writable files).

No, the number of signal is decided by `CommonDirectory.countTargetDirectories()` which skips trash folders but include those created by other users.

2022-11-30 13:35 UTC, JasonFengJ9 commented
The user issue https://github.com/eclipse-openj9/openj9/issues/15459 has been closed w/o further action required, this PR is not needed.
Created https://github.com/eclipse-openj9/openj9/issues/16390 for future enhancement.

2022-11-30 13:35 UTC, closed without merging