Re-order the shutdown hook sequence
eclipse-openj9/openj9 pull request #15498
Opened 2022-07-06 21:14 UTC by tajila

Re-order the shutdown hook sequence

The new implementation of Thread.getAllThreads() makes use of method
references. This requires that a new MethodHandleNatives$CallSiteContext
is created. This registers a PhantomCleanable with the commoncleaner and
circumvents what we are attempting to achieve with
CleanerShutdown.shutdownCleaner(). We can resolve this issue re-ordering
operations such that shutdownCleaner is the last operation before we
fallback to the sending the interrupt.

Fixes: https://github.com/eclipse-openj9/openj9/issues/15453

Related: https://github.com/eclipse-openj9/openj9/issues/15408

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

2022-07-06 21:15 UTC, tajila commented
jenkins test sanity xlinux jdk19

2022-07-07 15:37 UTC, tajila commented
10x Grinder passed 10/10

2022-07-07 15:41 UTC, tajila commented
@keithc-ca Ive made the requested changes

2022-07-07 16:41 UTC, keithc-ca commented
After looking more closely at this, I have a number of questions/comments:
* How do we know that the `Common-Cleaner` thread has actually been created before the shutdown hook runs? If it hasn't, and something triggers its creation within `shutdownCleaner()`, it won't be among the threads enumerated earlier and so it can't be stopped.
* Have you tested this change with earlier versions (11, 17 & 18)?
* This shutdown code is rather fragile; it may be broken by an application creating a thread named "Common-Cleaner" or a thread group named "InnocuousThreadGroup".
* If the "InnocuousThreadGroup" is not found, a NullPointerException will be thrown.

2022-07-07 18:43 UTC, tajila commented
> How do we know that the Common-Cleaner thread has actually been created before the shutdown hook runs? 

Common-cleaner is created as part of JCL initialization, so it will always exist in a successful `JNI_CreateJavaVM` and it will exist very early (pre-main). If startup is not successful, then we dont bother calling `DestroyJavaVM` which is what triggers the shutdownhooks.

> This shutdown code is rather fragile; it may be broken by an application creating a thread named "Common-Cleaner" or a thread group named "InnocuousThreadGroup".
> If the "InnocuousThreadGroup" is not found, a NullPointerException will be thrown.

Likewise "InnocuousThreadGroup" will always exist as its also created in JCL initialization. It is possible for a user to create a new threadGroup with the same name as an existing one, so I'll modify that behaviour.

> Have you tested this change with earlier versions (11, 17 & 18)?

We have existing tests that rely on this behaviour to function properly, memleaks, thrstatetest, gcRegressionTests, etc. All of these have been passing until jdk19.

2022-07-08 13:57 UTC, tajila commented
jenkins test sanity xlinux jdk11

2022-07-08 13:58 UTC, tajila commented on jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
> +import jdk.internal.misc.InnocuousThread;
ill fix the ordering of imports

2022-07-08 16:47 UTC, tajila commented
jdk11 PR build - https://openj9-jenkins.osuosl.org/view/Pull%20Requests/job/PullRequest-OpenJ9/2402/

2022-07-08 18:39 UTC, tajila commented
thrstatetest grinder on jdk11: https://openj9-jenkins.osuosl.org/job/Grinder/1111/

2022-07-08 18:47 UTC, tajila commented
jenkins test sanity xlinux jdk17,jdk18

2022-07-08 20:11 UTC, tajila commented
jenkins test sanity xlinux jdk11

2022-07-09 12:04 UTC, tajila commented
jdk11 grinder 10/10: https://openj9-jenkins.osuosl.org/job/Grinder/1112/tapResults/

2022-07-09 12:04 UTC, tajila commented
jenkins test sanity xlinux jdk17,jdk18

2022-07-11 13:40 UTC, tajila commented
jdk 17 grinder 10/10 https://openj9-jenkins.osuosl.org/job/Grinder/1113/
jdk 18 grinder 10/10 https://openj9-jenkins.osuosl.org/job/Grinder/1114/

2022-07-11 21:18 UTC, keithc-ca requested changes

2022-07-11 21:18 UTC, keithc-ca commented on jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
> +				ThreadGroup threadGroup = null;
Please remove the redundant initialization.

2022-07-11 21:18 UTC, keithc-ca commented on jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
> +				} catch (ReflectiveOperationException e) {
Can you sharpen this catch clause, please?
```
	} catch (IllegalAccessException | NoSuchFieldException e) {
```

2022-07-11 21:18 UTC, keithc-ca commented on jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
>  				Thread threads[] = null;
Please use normal array declaration syntax and remove the redundant initialization:
```
    Thread[] threads;
```

2022-07-12 13:01 UTC, keithc-ca commented
jenkins test sanity xlinux jdk11,jdk19

2022-07-12 17:50 UTC, tajila commented
The failure is:
```
FAILED: testServerUnreachableForAWhile
java.lang.AssertionError: Failed to properly start server, it terminated prematurely with exit value: 1
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.startProcess(JITServerTest.java:271)
	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:407)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

I dont think its related to this change, https://github.com/eclipse-openj9/openj9/issues/9197 looks similar

Running grinder https://openj9-jenkins.osuosl.org/job/Grinder/1129/

2022-07-12 17:52 UTC, keithc-ca approved these changes

2022-07-12 17:54 UTC, merged