Update jvmtiGetThreadGroupChildren for java 19
eclipse-openj9/openj9 pull request #15539
Opened 2022-07-13 19:21 UTC by EricYangIBM

The ThreadGroup class does not store its threads anymore and child groups
are separated into "groups" and "weaks" ThreadGroup arrays.

Issue: #15183
Signed-off-by: Eric Yang <eric.yang@ibm.com>

2022-07-20 15:00 UTC, babsingh requested changes
The commit message/description should include few lines on how the `threads` and `groups` arrays are created for Java 19+. It will make it easier to follow the Java19+ implementation.

2022-07-20 16:46 UTC, EricYangIBM commented on runtime/jvmti/jvmtiThreadGroup.c
> +		*rv_threads = threads;
We return the actual number of threads in the array so it probably is fine

2022-07-20 16:48 UTC, EricYangIBM commented on runtime/jvmti/jvmtiThreadGroup.c
> +static jvmtiError getThreadGroupChildrenImpl(J9JavaVM *vm, J9VMThread *currentThread, jobject group,
In other files the `static jvmtiError` and function name are on the same line. Should I follow their formatting?

2022-07-20 16:52 UTC, babsingh commented on runtime/jvmti/jvmtiThreadGroup.c
> +static jvmtiError getThreadGroupChildrenImpl(J9JavaVM *vm, J9VMThread *currentThread, jobject group,
Match existing formatting. Also, you can keep multiple parameters on a single line if needed. It should be consistent.

2022-07-20 19:03 UTC, babsingh commented on runtime/jvmti/jvmtiThreadGroup.c
> +		*rv_threads = threads;
A lot of allocated memory will be unused if the filter excludes a lot of threads. Filter: include only platform threads which match the thread_group.

2022-07-20 19:03 UTC, babsingh commented on runtime/jvmti/jvmtiThreadGroup.c
> +		*rv_groups = groups;
A lot of allocated memory will be unused if a lot of weak references are null.

2022-07-20 19:09 UTC, babsingh commented
@EricYangIBM The commits can be squashed.

@tajila These changes should work fine. But, still doubtful about the memory allocated for `threads` and `groups` arrays which are returned from this method (see comments inlined in code). Should we create new arrays with smaller/required size and copy the elements from the bigger array and free the bigger array?

2022-07-21 14:40 UTC, EricYangIBM commented on runtime/jvmti/jvmtiThreadGroup.c
> +				if (J9VMJAVALANGTHREAD_STARTED(currentThread, threadObject)
According to your comment https://github.com/eclipse-openj9/openj9/issues/15183#issuecomment-1167767823
the J9VMThread link list does not include virtual threads.

2022-07-27 20:07 UTC, EricYangIBM commented on runtime/jvmti/jvmtiThreadGroup.c
> +			j9object_t threadObject = targetThread->threadObject;
To do: change to targetThread->carrierThreadObject

2022-08-04 18:46 UTC, tajila commented
> But, still doubtful about the memory allocated for threads and groups arrays which are returned from this method (see comments inlined in code). Should we create new arrays with smaller/required size and copy the elements from the bigger array and free the bigger array?

This is not going to return vthreads correct? If so, then I dont think returning a potentially larger buffer is a big deal as platform threads arent created as frequently

2022-08-04 18:46 UTC, tajila commented
It could be an optimization that is added later

2022-08-04 18:55 UTC, babsingh commented
> This is not going to return vthreads correct?

Vthreads will not be returned. See ref below. @EricYangIBM Can you add a comment in code and open an issue regarding this optimization for tracking purposes?

Ref: https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html#GetThreadGroupChildren

2022-08-04 19:07 UTC, EricYangIBM commented on runtime/jvmti/jvmtiThreadGroup.c
> +			j9object_t group = J9JAVAARRAYOFOBJECT_LOAD(currentThread, childrenGroups, i);
Done

2022-08-04 19:07 UTC, EricYangIBM commented
I will open the issue after this PR is merged (to link to the comment)

2022-08-04 19:13 UTC, babsingh commented
LGTM. The commits need to be squashed before the PR builds are launched.

2022-08-04 19:14 UTC, EricYangIBM commented
Squashed

2022-08-04 19:16 UTC, babsingh commented
jenkins compile win jdk19,jdk17

2022-08-04 19:17 UTC, babsingh commented
Does not work for me yet. Need to wait for @AdamBrousseau to add me.

2022-08-05 14:56 UTC, babsingh commented
jenkins compile win jdk19,jdk17

2022-08-05 17:06 UTC, babsingh commented
These JVMTI changes should only impact the `gtgc001` test, which has been enabled and passes for JDK17 and JDK19. 

> https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal/75/

`jit_vich_0_FAILED` is unrelated to this PR. All tests in this suite pass but there is an error at the end (`Invalid JIT return address`).
```
===============================================
JIT_Test suite
Total tests run: 18, Failures: 0, Skips: 0
===============================================

*** Invalid JIT return address 000000037A4175E0 in 000000016FBDFD98

jit_vich_0_FAILED
```

2022-08-05 17:10 UTC, babsingh approved these changes
LGTM. Opened https://github.com/eclipse-openj9/openj9/issues/15673 for the JIT failure.

2022-08-05 17:11 UTC, babsingh commented
Still can't merge the PR. Need to wait for @AdamBrousseau to give the required permissions.

2022-08-05 17:18 UTC, AdamBrousseau commented
>Still can't merge the PR

This is an Eclipse Github team thing. It should be automatic. If it's not working then I would open an Eclipse ticket.
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues?sort=created_date&state=opened

2022-08-10 20:32 UTC, merged