NPE extended message generation missed j9mem_free_memory calls
eclipse-openj9/openj9 pull request #15550
Opened 2022-07-15 17:33 UTC by JasonFengJ9

NPE extended message generation missed `j9mem_free_memory()` calls

[Internal personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/13581/)

fixes https://github.com/ibmruntimes/Semeru-Runtimes/issues/32

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

2022-07-18 17:30 UTC, pshipton commented
jenkins compile win jdk8

2022-07-18 21:00 UTC, keithc-ca requested changes

2022-07-18 22:10 UTC, JasonFengJ9 commented on runtime/vm/extendedMessageNPE.cpp
>  				*npeMsg = (char *)npeMsgObjref;
Removed.

2022-07-18 23:47 UTC, keithc-ca commented
jenkins compile win,win32 jdk8

2022-07-18 23:47 UTC, keithc-ca approved these changes

2022-07-19 00:06 UTC, pshipton approved these changes

2022-07-19 03:50 UTC, merged