Revert "Preserve ymm/zmm registers on x"
eclipse-openj9/openj9 pull request #15999
Opened 2022-09-27 21:09 UTC by BradleyWood

This reverts #14632.

2022-09-28 02:18 UTC, 0xdaryl commented
This will require an explanation for why this is necessary.  Can you add the rationale to the commit message please?

2022-09-28 02:19 UTC, 0xdaryl commented
Jenkins test sanity xlinux,osx,win jdk17

In the meantime, I'll launch PR testing.

2022-09-28 13:25 UTC, 0xdaryl commented
For the record lest it get lost in the next push, JDK17 builds and sanity testing passed on all platforms.

2022-09-28 15:08 UTC, 0xdaryl commented
Can you also add: "A previous attempt at disabling just the extended vector register preservation did not recoup the performance, but only completely reverting this PR restored the regression.  This suggests there is something with the way the helpers have been restructured that is causing the performance degradation.  This PR will be reverted while the cause is investigated."

2022-09-28 20:11 UTC, pshipton commented
Is this something we'll want in the 0.35 release?

2022-09-28 20:16 UTC, pshipton requested changes

2022-09-28 20:16 UTC, pshipton commented on runtime/jilgen/jilconsts.c
> + * Copyright (c) 1991, 2021 IBM Corp. and others
This copyright shouldn't be reverted to 2021, the file is modified by other commits in 2022.

2022-09-28 20:16 UTC, pshipton commented on runtime/oti/xhelpers.m4
> +dnl Copyright (c) 1991, 2021 IBM Corp. and others
This copyright shouldn't be reverted to 2021, the file is modified by other commits in 2022.

2022-09-29 11:38 UTC, 0xdaryl approved these changes
Recent pushes have only been to commit messages or comments.  No need to re-run CI.

2022-09-29 11:39 UTC, merged

2022-09-29 11:45 UTC, 0xdaryl commented
> Is this something we'll want in the 0.35 release?

Yes, if it is not too late and this PR has a chance to soak in at least one test cycle.

@BradleyWood : could you prepare the 0.35 PR and have it ready for us to merge please?