Adds implementation for accessFlags() in Class.java
eclipse-openj9/openj9 pull request #16217
Opened 2022-10-27 20:08 UTC by thallium

Fixes: #15933
Signed-off-by: Gengchen Tuo <gengchen.tuo@ibm.com>

2022-10-27 20:09 UTC, thallium commented
FYI @hangshao0 @fengxue-IS

2022-10-27 20:18 UTC, hangshao0 commented
Did you compare the behaviour of this change with OpenJDK ?

2022-10-27 20:24 UTC, pshipton commented
Pls ensure we're passing the OpenJDK test java/lang/reflect/AccessFlag/ClassAccessFlagTest.java on jdk20, currently this test is failing. https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1456/
```
17:29:35  java.lang.NullPointerException: Cannot invoke "java.util.Set.toString()" because the return value of "java.lang.Class.accessFlags()" is null
17:29:35  	at ClassAccessFlagTest.checkClass(ClassAccessFlagTest.java:79)
17:29:35  	at ClassAccessFlagTest.checkClasses(ClassAccessFlagTest.java:71)
17:29:35  	at ClassAccessFlagTest.main(ClassAccessFlagTest.java:60)
```

jenkins compile amac jdknext

2022-10-27 20:48 UTC, thallium commented
> Pls ensure we're passing the OpenJDK test java/lang/reflect/AccessFlag/ClassAccessFlagTest.java on jdk20,

Passed on my local machine.

2022-10-27 20:52 UTC, hangshao0 commented on jcl/src/java.base/share/classes/java/lang/Class.java
> +		int rawModifiers = getModifiersImpl();
Is there a reason to use `getModifiersImpl()` rather than `getModifiers()` ? We do not want to duplicate the code of `getModifiers()`.

2022-10-27 21:13 UTC, pshipton commented
Grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1462/ passed too.

Rerun link
https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?TARGET=jdk_custom&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=mac11-aarch64-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_aarch64_mac_Personal%2F52%2FOpenJ9-JDKnext-aarch64_mac-20221028-072923.tar.gz&DAYS_TO_KEEP=7&ADOPTOPENJDK_BRANCH=master&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&JDK_VERSION=20&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=master&OPENJ9_SHA=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=&JDK_IMPL=openj9&AUTO_DETECT=true&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=AdoptOpenJDK%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=AdoptOpenJDK%3Amaster&JDK_VENDOR=&BUILDS_TO_KEEP=60&JVM_OPTIONS=&PARALLEL=None

2022-10-27 22:53 UTC, fengxue-IS requested changes
One additional point to consider is that the Java EA spec on [Class.accessFlags()](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Class.html#accessFlags()) didn't fully document all possible cases with array classes
> The values of its other access flags are not determined by this specification.

So behaviour beyond Public/Private/Protected/Final can change in the future.

Note 2:
I am not sure if we actually need the masking to be done here as `javac` should be generating the correct access flags in the classfile and a class with an incorrect flag will throw exception in `AccessFlag.maskToAccessFlags`. we shouldn't try to hide these possible exceptions through masking.

@thallium can you try if directly using results from `getModifiersImpl()` passes the tests?
Can you also verify the case where the class is a module? (with `module-info.class` ie.
`Class<?> moduleClass = ClassLoader.getSystemClassLoader().findClass("java.base", "module-info");` )

2022-10-27 22:53 UTC, fengxue-IS commented on jcl/src/java.base/share/classes/java/lang/Class.java
> +			rawModifiers &= Modifier.PUBLIC | Modifier.PRIVATE | Modifier.PROTECTED |
Missing the `MODULE` flag

2022-10-27 22:53 UTC, fengxue-IS commented on jcl/src/java.base/share/classes/java/lang/Class.java
> +						Modifier.ABSTRACT | Modifier.FINAL;
Per function header, 
> For an array class, the PUBLIC, PRIVATE and PROTECTED access flags should be the
same as those of its component type, and the FINAL access flag should always present.

Modifier.FINAL should always be part of this

2022-10-27 22:53 UTC, fengxue-IS commented on jcl/src/java.base/share/classes/java/lang/Class.java
> +						Modifier.ABSTRACT | Modifier.FINAL;
A note on this, the native impl of getModifiersImpl() forces ABSTRACT and FINAL to be added to the component type's modifiers, so forcing FINAL here may not be needed.

2022-10-28 15:05 UTC, hangshao0 commented on jcl/src/java.base/share/classes/java/lang/Class.java
> +		int rawModifiers = getModifiersImpl();
OK, I see a comment is added explaining this.

2022-10-28 15:56 UTC, fengxue-IS commented
Just realized that classes with ACC_Module flag is not allowed to be loaded by classloader, so please disregard my comment on testing with `module-info.class`, I am not sure how the Module access flag is suppose to be validated in testing.

2022-10-28 16:00 UTC, thallium commented
> can you try if directly using results from `getModifiersImpl()` passes the tests?

Unfortunately this doesn't work.

2022-10-28 18:01 UTC, hangshao0 approved these changes

2022-11-15 19:41 UTC, fengxue-IS approved these changes
@babsingh can you take a look, and launch the PR build if you are fine with the changes

2022-11-16 17:10 UTC, babsingh requested changes
@thallium Also, resolve old comments which have been resolved.

2022-11-16 17:10 UTC, babsingh commented on jcl/src/java.base/share/classes/java/lang/Class.java
> +	 * {@return an unmodifiable set of the {@linkplain AccessFlag access
The correct ordering for the function description is `@brief`, `@param` and `@return`. Here, `@return` is before `@brief`.

2022-11-17 16:27 UTC, babsingh commented
jenkins test sanity amac jdknext

2022-11-17 16:27 UTC, babsingh commented
jenkins compile zlinux jdk11

2022-11-17 16:30 UTC, babsingh commented
@thallium can you reconfirm that `java/lang/reflect/AccessFlag/ClassAccessFlagTest.java` passes with the latest changes?

2022-11-17 17:11 UTC, thallium commented
> @thallium can you reconfirm that `java/lang/reflect/AccessFlag/ClassAccessFlagTest.java` passes with the latest changes?

Yes, still passes

2022-11-17 17:59 UTC, babsingh approved these changes

2022-11-17 17:59 UTC, merged