Update criu test to ignore tid issues
eclipse-openj9/openj9 pull request #16373
Opened 2022-11-28 15:04 UTC by tajila

Update criu test to ignore tid issues

If CRIU can't acquire the origin thread IDs it will fail, nothing can be done about this. update tests to ignore this failure. Long term we may need to transform all tests to container tests.

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

2022-11-28 15:05 UTC, tajila commented
Jenkins test sanity xlinuxcriu jdk17

2022-11-28 21:49 UTC, tajila commented
200x grinder - https://openj9-jenkins.osuosl.org/job/Grinder/1531/

2022-11-29 13:45 UTC, tajila commented
@llxia I found the following issue in the grinder https://openj9-jenkins.osuosl.org/job/Grinder_testList_1/80/tapResults/

```
Output from test:
 [ERR] bash: /home/jenkins/workspace/Grinder_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: No such file or directory
```

2022-11-29 15:43 UTC, tajila commented
@babsingh please review

2022-11-29 16:25 UTC, llxia commented
re https://github.com/eclipse-openj9/openj9/pull/16373#issuecomment-1330674787, no, I haven't seen this before. Please let us know if this occurs again. Thanks

2022-11-29 16:35 UTC, tajila commented
Jenkins test sanity xlinuxcriu jdk17

2022-11-29 16:44 UTC, babsingh requested changes
LGTM, other than minor formatting suggestions for the comment.

2022-11-29 16:44 UTC, babsingh commented on test/functional/cmdLineTests/criu/criu.xml
> +    <!-- If CRIU can't acquire the original thread IDs it will fail, nothing can be done about this -->
```suggestion
    <!-- If CRIU can't acquire the original thread IDs, this test will fail. Nothing can be done about this failure. -->
```

2022-11-29 16:44 UTC, babsingh commented on test/functional/cmdLineTests/criu/criu_keepCheckpoint.xml
> +    <!-- In the past the failure below was caused by an issue where criu can't be found on the PATH -->
```suggestion
    <!-- In the past, the failure below was caused by an issue where CRIU can't be found on the PATH. -->
```

2022-11-29 17:56 UTC, tajila commented
Existing PR test, https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK17_x86-64_linux_criu/152/

2022-11-29 17:59 UTC, tajila commented
Changes are ready for another look

2022-11-29 18:53 UTC, babsingh approved these changes
LGTM. @llxia Do the changes look good to you?

2022-11-29 20:25 UTC, llxia approved these changes
LGTM

2022-11-30 01:01 UTC, babsingh commented
> https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal/38/tapResults/

Noticed the same failures, which were reported in https://github.com/eclipse-openj9/openj9/pull/16376#issuecomment-1331485854.

```
FAILED: test_isAnnotationPresent
java.lang.AssertionError: Following exception occured : Cannot invoke "java.io.File.deleteOnExit()" because "folder" is null
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@43abce9b(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_Personal_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.annotationPackage.Test_PackageAnnotation2.test_isAnnotationPresent(Test_PackageAnnotation2.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@43abce9b(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_Personal_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
...

FAILED: test_fileHasOtherAccess
java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.fail(Assert.java:103)
	at org.openj9.test.jdk.internal.agent.Test_FileSystem_Base.testSetup(Test_FileSystem_Base.java:47)
...
```

2022-11-30 04:06 UTC, babsingh commented
Jenkins test sanity xlinuxcriu jdk17

2022-11-30 12:41 UTC, merged