Fix up potential stale pointer after GC
eclipse-openj9/openj9 pull request #16414
Opened 2022-12-04 23:17 UTC by tajila

Fix up potential stale pointer after GC

Fixes https://github.com/eclipse-openj9/openj9/issues/16351

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

2022-12-04 23:17 UTC, tajila commented
jenkins test sanity amac jdk19

2022-12-05 02:54 UTC, tajila commented
jenkins test sanity win jdk19

2022-12-05 03:22 UTC, babsingh requested changes
The PR builds don't need to be relaunched. The old PR builds are still good since only the comment was updated.
- **amac:** https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/3109 (**PASSED**)
- **win_x64:** https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/3110
- **pLinux:** https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/3111

2022-12-05 03:22 UTC, babsingh commented on runtime/j9vm/javanextvmi.cpp
> +			/* re-fetch as the memory allocation above may have moved the object */
Please update the comment's formatting to match the surrounding comments.
```suggestion
			/* Re-fetch as the memory allocation above may have moved the object. */
```

2022-12-05 03:23 UTC, babsingh commented on runtime/j9vm/javanextvmi.cpp
> +			/* re-fetch as the memory allocation above may have moved the object */
I was under the assumption that the objects won't move under VM access. Why is this an exception?

2022-12-05 16:32 UTC, babsingh commented on runtime/j9vm/javanextvmi.cpp
> +			threadObj = J9_JNI_UNWRAP_REFERENCE(thread);
`j9jni_createGlobalRef` only allocates from a J9 Pool. `mmFuncs->J9AllocateObject` (line 341) is the GC trigger point. So, the re-fetch should move to line 346 after `J9AllocateObject` is invoked.

2022-12-05 16:59 UTC, tajila commented
jenkins test sanity amac jdk19

2022-12-05 18:33 UTC, babsingh approved these changes

2022-12-05 18:33 UTC, merged

2022-12-05 18:58 UTC, keithc-ca commented on runtime/j9vm/javanextvmi.cpp
> +		threadObj = J9_JNI_UNWRAP_REFERENCE(thread);
By the same reasoning, `rootVirtualThread` may have moved as well.