Support for Scoped Values (JEP 429)
eclipse-openj9/openj9 pull request #16678
Opened 2023-02-07 18:50 UTC by babsingh

In JDK20, `extentLocalCache` is renamed to `scopedValueCache`.

JDK19 and JDK20 changes are completely segregated to avoid
cross-contamination if the implementation differs a lot across
JDK versions.

TODO: `Thread.findScopedValueBindings` needs to be implemented.
This is tracked in #16677.

Related: #16439
Fixes: #16657

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

2023-02-07 21:53 UTC, babsingh commented
This PR contains changes related to the code, which fixed the failures reported in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/531#issuecomment-1414508378. 

Started a personal build (JDK19 + JDK20, sanity.functional + sanity.openjdk): https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/15472/.

fyi @ChengJin01 @JasonFengJ9 @tajila @pshipton

2023-02-09 02:52 UTC, babsingh commented
In the above personal build, `WithScopedValue` passes and all other OpenJDK test failures are known. This PR is ready to be reviewed. @JasonFengJ9 Requesting your review.

2023-02-09 16:38 UTC, babsingh commented
@JasonFengJ9 Addressed all your feedback. Removed `Access.java` changes since it is already correct.

2023-02-09 18:56 UTC, JasonFengJ9 approved these changes
LGTM

2023-02-09 18:57 UTC, JasonFengJ9 commented
@keithc-ca please review/merge.

2023-02-09 19:39 UTC, keithc-ca requested changes

2023-02-09 19:39 UTC, keithc-ca commented on runtime/jcl/uma/se19only_exports.xml
> +	SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
Please remove the leading whitespace here.

2023-02-09 19:39 UTC, keithc-ca commented on runtime/jcl/common/thread.cpp
> + * @return void
Please don't make these changes. Periods are not wanted for `@param` entries and `@return` isn't appropriate for a function that doesn't return anything.

2023-02-09 19:39 UTC, keithc-ca commented on runtime/jcl/exports.cmake
> +		Java_java_lang_Thread_findScopedValueBindings
Please list names alphabetically.

2023-02-09 19:39 UTC, keithc-ca commented on runtime/jcl/module.xml
> +	<xi:include href="uma/se19only_exports.xml"></xi:include>
Please order these includes consistently with the groups below.

2023-02-09 19:39 UTC, keithc-ca commented on runtime/jcl/uma/se20_exports.xml
>  	<export name="Java_java_lang_Thread_ensureMaterializedForStackWalk" />
Please list names alphabetically.

2023-02-09 19:45 UTC, keithc-ca commented
Given the short life-expectancy of Java 19, perhaps it makes sense to just use the new name `scopedValueCache` in the Java 19 implementations? That might reduce the work to be done later should we decide to remove things specific to Java 19.

2023-02-13 05:21 UTC, babsingh commented
@keithc-ca Addressed all your feedback.

2023-02-14 19:16 UTC, keithc-ca commented on runtime/jcl/common/thread.cpp
> +	/* TODO: Implement. */
The comment should refer to the issue (https://github.com/eclipse-openj9/openj9/issues/16677) instead of this pull request.

2023-02-14 19:42 UTC, babsingh commented on runtime/jcl/common/thread.cpp
> +	/* TODO: Implement. */
Updated from https://github.com/eclipse-openj9/openj9/pull/16678 to https://github.com/eclipse-openj9/openj9/pull/16677.

2023-02-14 20:05 UTC, keithc-ca commented on runtime/jcl/common/thread.cpp
> +	/* TODO: Implement. See https://github.com/eclipse-openj9/openj9/pull/16677. */
This URL should be .../**issues**/...

2023-02-14 20:08 UTC, babsingh commented on runtime/jcl/common/thread.cpp
> +	/* TODO: Implement. See https://github.com/eclipse-openj9/openj9/pull/16677. */
Updated.

2023-02-14 20:24 UTC, keithc-ca commented
Jenkins test sanity alinux64 jdk19,jdk20

2023-02-14 22:43 UTC, keithc-ca approved these changes

2023-02-14 22:43 UTC, merged