Remove setImmutableField on currentThread for JDK19 and up
eclipse-openj9/openj9 pull request #17009
Opened 2023-03-23 14:20 UTC by a7ehuo

`Thread.currentThread` can be changed by JCL in JDK19 and up. Set it as volatile for JDK19 and up.

Add `isJ9VMThreadCurrentThreadImmutable` in FrontEnd to query whether or not `Thread.currentThread` is immutable based on `JAVA_SPEC_VERSION`.

Issue #16258

2023-03-23 14:58 UTC, a7ehuo commented
Changed to `WIP`. Just got the result from extended.system test on zLinux and need to look at a failure in the test.

2023-03-23 15:37 UTC, 0xdaryl commented
Jenkins test sanity all jdk19

2023-03-23 15:38 UTC, a7ehuo commented
Removed `WIP`. Found the crash is in libj9vm29.so with `vmState=0xffffffff` in test `MathLoadTest_all_CS_5m_0`, which  is likely #16976 and my personal build doesn't have the fix for it yet

2023-03-23 15:39 UTC, pshipton commented
Jenkins test sanity.openjdk all jdk19

2023-03-23 16:46 UTC, 0xdaryl commented
I was chatting with @mstoodle about future-proofing JDK-specific changes like this for JIT server.  Toward that goal, rather than using `#ifdef`s within this function, could you introduce a FrontEnd query (something like `isJ9VMThreadCurrentThreadImmutable()`) that returns `true` for JDK < 19 and `false` for JDK >= 19 and then use the function appropriately in `findOrCreateCurrentThreadSymbolRef()`?  In the FrontEnd implementation of that you can introduce the `#if JAVA_SPEC_VERSION` logic.

2023-03-23 17:44 UTC, a7ehuo commented
>could you introduce a FrontEnd query (something like isJ9VMThreadCurrentThreadImmutable()) that returns true for JDK < 19 and false for JDK >= 19 and then use the function appropriately in findOrCreateCurrentThreadSymbolRef()? 

@0xdaryl The change is made in 41166e5. Ready for another review. Thanks!

2023-03-23 17:44 UTC, 0xdaryl commented
Jenkins test sanity,sanity.openjdk all jdk19

2023-03-23 18:08 UTC, pshipton commented
I stopped the old PR build https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/3550/, you may see some check status reflecting that, which will be overwritten when the new PR build https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/3551/ completes.

2023-03-23 19:00 UTC, pshipton requested changes
Before merging, we need to consider there appear to be new failures not seen before in the testing for this fix. https://github.com/eclipse-openj9/openj9/issues/16258#issuecomment-1481737493

2023-03-24 19:00 UTC, a7ehuo commented
` Grinder ID 31915` on `jdk_lang_1` with this change. **30x, all passed**

2023-03-24 19:10 UTC, pshipton approved these changes

2023-03-24 19:36 UTC, 0xdaryl commented
All tests and grinders have succeeded (see #16258 for more details on the grinders).  Merging.

@a7ehuo : Please create a 0.37 PR with this change as well.  The problem is unique to Loom and doesn't apply to 0.38.

2023-03-24 19:36 UTC, merged

2023-03-24 20:04 UTC, a7ehuo commented
>Please create a 0.37 PR with this change as well. The problem is unique to Loom and doesn't apply to 0.38.

v0.37.0-release PR: https://github.com/eclipse-openj9/openj9/pull/17021