Add a walk state flag to skip methods with the JvmtiMountTransition annotation
eclipse-openj9/openj9 pull request #17758
Opened 2023-07-07 21:22 UTC by thallium

Since it's only related to JVMTI, a walk state flag is added to enable the behaviour when doing JVMTI-related stack walk.

Related: https://github.com/eclipse-openj9/openj9/issues/17490

2023-07-07 21:23 UTC, thallium commented
@babsingh FYI

2023-07-10 18:22 UTC, babsingh requested changes

2023-07-10 18:22 UTC, babsingh commented on runtime/oti/j9.h
>  #if defined(OPENJ9_BUILD)
Add a new line.
```suggestion
#if JAVA_SPEC_VERSION >= 20
#define J9_IS_JVMTI_MOUNT_TRANSITION(method) \
	((NULL != (method)) && (J9_ARE_ANY_BITS_SET(getExtendedModifiersDataFromROMMethod(J9_ROM_METHOD_FROM_RAM_METHOD(method)), CFR_METHOD_EXT_JVMTIMOUNTTRANSITION_ANNOTATION)))
#endif /* JAVA_SPEC_VERSION >= 20 */

#if defined(OPENJ9_BUILD)
```

2023-07-10 18:22 UTC, babsingh commented on runtime/vm/swalk.c
> +		}
To be consistent with https://github.com/eclipse-openj9/openj9/pull/16654, the code changes in this PR should be wrapped with `JAVA_SPEC_VERSION >= 20`.
```suggestion
#if JAVA_SPEC_VERSION >= 20
		/* Skip methods with JvmtiMountTransition annotation */
		if (J9_ARE_ALL_BITS_SET(walkState->flags, J9_STACKWALK_SKIP_JVMTI_MOUNT_TRANSITION_FRAMES)
			&& J9_IS_JVMTI_MOUNT_TRANSITION(walkState->method)
		) {
			return J9_STACKWALK_KEEP_ITERATING;
		}
#endif /* JAVA_SPEC_VERSION >= 20 */
```

2023-07-10 18:22 UTC, babsingh commented on runtime/oti/j9consts.h
> +#define J9_STACKWALK_SKIP_JVMTI_MOUNT_TRANSITION_FRAMES 0x1000
Macro definitions don't need `JAVA_SPEC_VERSION >= 20`.

2023-07-10 19:17 UTC, gacholio commented
This stuff really doesn't belong in the stack walker (I know previous hacks for hidden have made it in). Really, it should be handled in the frame iterators, much like we do to hide the old reflect implementation).

2023-07-10 19:24 UTC, gacholio commented on runtime/jvmti/jvmtiHelpers.c
> +	walkState->flags = J9_STACKWALK_ITERATE_FRAMES | J9_STACKWALK_INCLUDE_NATIVES | J9_STACKWALK_VISIBLE_ONLY | J9_STACKWALK_RECORD_BYTECODE_PC_OFFSET | J9_STACKWALK_MAINTAIN_REGISTER_MAP | J9_STACKWALK
This is certainly a place that should not be changed - this wants the true view of the stack, not a user-facing one.

2023-07-10 19:25 UTC, gacholio commented
The only place using the new flag is using it incorrectly as far as I can see, so we should probably just abandon this PR.

2023-07-26 21:04 UTC, closed without merging