Add stronger guarantees to System.gc()
eclipse-openj9/openj9 pull request #18044
Opened 2023-08-30 13:49 UTC by tajila

The JCL code expects that when System.GC() is called a GC occurs and finalizable objects are finalized. Historically, J9 has never provided this guarantee. We have often had to modify tests to ensure a GC is triggered at the appropriate time. Increasingly, we are finding that more and more tests rely on this behaviour, and most importantly, core JCL code now relies on this behaviour. This PR ensures that a call to System.gc() triggers a GC and runs finalization.

2023-08-30 13:52 UTC, tajila commented
jenkins test sanity alinux64 jdk21

2023-08-30 13:55 UTC, tajila commented
jenkins test sanity alinux64 jdk21

2023-08-30 14:23 UTC, gacholio approved these changes

2023-08-30 14:24 UTC, gacholio commented
Finalization has been deprecated for many releases - it seems odd that the JCL would rely on unspecified and completely unreliable behaviour.

2023-08-30 14:27 UTC, dmitripivkine approved these changes

2023-08-30 14:41 UTC, tajila commented
jenkins compile win jdk8

2023-08-30 17:49 UTC, tajila commented
@gacholio I had to add an explicit `internalReleaseVMAccess` because finalization cannot be run when VMAccess is held

2023-08-30 18:03 UTC, tajila commented
jenkins test sanity alinux64 jdk21

2023-08-30 18:09 UTC, gacholio requested changes
This is no longer valid. You will need to reacquire VM access and exit the VM properly.

2023-08-30 18:37 UTC, gacholio commented
`Java_java_lang_ref_Finalizer_runFinalizationImpl` appears to make the same incorrect assumption about VM access and enter/exit - consider fixing this here as well.

2023-08-30 18:38 UTC, gacholio commented
Also note the ifdefs in the native - those should probably be mirrored in the JVM call.

2023-08-30 19:33 UTC, dmitripivkine commented
> Also note that this doesn't really fix anything - the finalizers themselves run on another thread, so there's no guarantee that any finalization has taken place when the JVM function / native method returns.
> 
> @dmitripivkine Please correct me if `runFinalization` does in fact ensure that finalizers have completed before returning.

 The idea of `runFinalization` is to force Finalizer threads run non-stop until queue is empty.

2023-08-30 19:36 UTC, gacholio commented
> The idea of `runFinalization` is to force Finalizer threads run non-stop until queue is empty.

Does this actually mean that all existing finalizers, and any that are created during the call will be processed? The queue would technically be empty while the finalizer was processing the last object in the queue.

2023-08-30 19:39 UTC, dmitripivkine commented
> > The idea of `runFinalization` is to force Finalizer threads run non-stop until queue is empty.
> 
> Does this actually mean that all existing finalizers, and any that are created during the call will be processed? The queue would technically be empty while the finalizer was processing the last object in the queue.

I see your point, I will check.

2023-08-30 20:34 UTC, tajila commented
jenkins test sanity alinux64 jdk21

2023-08-31 05:06 UTC, gacholio approved these changes
Regardless of Dmitri's investigation, this is the best we can do (if there are any edge cases they'll be in the GC code). The VM access changes are not strictly necessary, in that atomic-free is currently tolerant of mistakes, but I'd rather see the right thing done, particularly in these cases where the guts of the work are potentially large.

2023-08-31 12:36 UTC, tajila commented
The failure was 

```
22:56:31.330 0x11200j9vmutil(j9vm).15     *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK21_aarch64_linux_Personal/openj9/runtime/util/mthutil.c:600: ((((uintptr_t)-1) != methodIndex))
```

2023-08-31 15:28 UTC, merged

2023-08-31 17:42 UTC, keithc-ca commented on runtime/sunvmi/sunvmi.c
> +	mmFuncs->j9gc_modron_global_collect(currentThread);
Perhaps a comment is warranted here explaining why `j9gc_modron_global_collect()` is run twice?

2023-09-05 14:49 UTC, pshipton commented
Created a doc issue https://github.com/eclipse-openj9/openj9-docs/issues/1161