Pass threadObject to walkContinuationStackFrames
eclipse-openj9/openj9 pull request #18180
Opened 2023-09-21 20:09 UTC by babsingh

threadObject is used in jvmtiFollowReferences.

Related: #17712

2023-10-04 16:12 UTC, fengxue-IS requested changes

2023-10-04 16:12 UTC, fengxue-IS commented on runtime/compiler/control/HookedByTheJit.cpp
>  	J9InternalVMFunctions *vmFuncs = vmThread->javaVM->internalVMFunctions;
please also correct the indentation here

2023-10-04 16:12 UTC, fengxue-IS commented on runtime/compiler/control/HookedByTheJit.cpp
> +      if (NULL != carrierThread)
please use `VM_ContinuationHelpers::isFullyMounted()` here to check if the continuation maps to vthread or carrier. It is possible that this code is triggered by STW GC while vthread is in the mount transition.

this also apply to other locations where you need to determine if continuation is mounted or not

2023-10-04 20:29 UTC, babsingh commented
@fengxue-IS I have addressed all of your feedback.

2023-10-04 20:50 UTC, fengxue-IS approved these changes
LGTM

2023-10-04 20:58 UTC, 0xdaryl approved these changes
JIT changes look fine.

2023-10-04 21:10 UTC, babsingh commented
The last push just updated the commit message to reflect the latest changes. Also, the PR description was updated.

2023-10-04 21:10 UTC, babsingh commented
jenkins test sanity zlinux jdk11,jdk21

2023-10-04 21:10 UTC, babsingh commented
jenkins compile win jdk11,jdk21

2023-10-05 13:06 UTC, amicic commented
While I see an improvement, isn't there still a problem JVMTI walking stack frames of while they are potentially changing (of a mounted VT)?
Concurrent GCs have a whole protocol to ensure we they don't walk it, while VT is mounted (and VT does not get mounted while GC walks it).
A more basic question for my understanding: how is this functionality safe even with just ordinary/platform threads without ensuring the thread does not have VM access (for example by acquiring exclusive VM access)?

2023-10-05 14:15 UTC, babsingh commented
re https://github.com/eclipse-openj9/openj9/pull/18180#issuecomment-1748862592:

There is synchronization code which prevents virtual threads to be mounted or unmounted while they are being inspected via JVMTI.

2023-10-05 14:29 UTC, babsingh commented
The PR builds look good except the known failure with details below.
 
> https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal/38/

`cmdLineTester_criu_random_0` failure is a known issue: https://github.com/eclipse-openj9/openj9/issues/14974#issuecomment-1695625140.

```
19:58:46  Testing: Second Restore of Criu Checkpoint Image
19:58:46  Test start time: 2023/10/04 23:58:46 Coordinated Universal Time
19:58:46  Running command: bash /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuRandomScript.sh /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java " -Denable.j9internal.checkpoint.security.api.debug=true " "SecondRestore"
19:58:46  Time spent starting: 12 milliseconds
19:58:46  Time spent executing: 35 milliseconds
19:58:46  Test result: FAILED
19:58:46  Output from test:
19:58:46   [OUT] start running script
19:58:46  >> Success condition was not found: [Output match: Different random values]
19:58:46  >> Success condition was not found: [Output match: Post-checkpoint]
19:58:46  >> Success condition was not found: [Output match: Second Restore]
19:58:46  >> Failure condition was not found: [Output match: CRIU is not enabled]
19:58:46  >> Failure condition was not found: [Output match: Operation not permitted]
19:58:46  >> Success condition was not found: [Output match: Thread pid mismatch]
19:58:46  >> Success condition was not found: [Output match: do not match expected]
19:58:46  >> Success condition was not found: [Output match: Unable to create a thread:]
19:58:46  >> Failure condition was not found: [Output match: Can't open dir cpData: No such file or directory]
19:58:46  >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
19:58:46  >> Failure condition was not found: [Output match: User requested Java dump using]
```

2023-10-05 14:44 UTC, amicic commented
> re [#18180 (comment)](https://github.com/eclipse-openj9/openj9/pull/18180#issuecomment-1748862592):
> 
> There is synchronization code which prevents virtual threads to be mounted or unmounted while they are being inspected via JVMTI.

This is good, but my original concern was more about the other way around - walking even if VT is already mounted. This change makes sure that a proper threadObject was snapshotted ahead of walk, but seems like JVMTI proceeds with the walk (of a stack that is potentially changing).

Another thing I'm curios about is the details of that synchronization - is there something we can share with Concurrent GC synchronization. It is outside of scope of these change - something we can talk about in person.

2023-10-05 17:39 UTC, babsingh commented
>  but seems like JVMTI proceeds with the walk (of a stack that is potentially changing).

In this case, JVMTI will either halt the thread or acquire exclusive VM access to prevent the thread stack from changing. In `jvmtiFollowReferences`, we acquire exclusive VM access.
 
> is there something we can share with Concurrent GC synchronization

@LinHu2016 and @fengxue-IS had a discussion about this in the past. JVMTI synchronization increments a counter or spins until the counter conditions are met. JVMTI synchronization is blocking and heavily dependent on spinning. The GC took a passive (non-blocking) approach to skip.

2023-10-05 19:27 UTC, babsingh commented
@amicic @dmitripivkine @0xdaryl Can I ask one of you to merge this PR if everything looks good?

2023-10-05 19:34 UTC, dmitripivkine commented
Failure in s390 build is unrelated (CRIU issue)

2023-10-05 19:34 UTC, merged