Refactor Checkpoint/Restore Code into its own class
eclipse-openj9/openj9 pull request #19157
Opened 2024-03-15 13:42 UTC by dsouzai

* Refactor Checkpoint/Restore code into its own class
* Add CR Runtime Thread
* Release Comp Monitor before proactive compilation
* Acquire VMAccess before queueing compilation proactively.

2024-03-15 13:58 UTC, dsouzai commented
@mpirvu could you please review?

2024-03-25 22:27 UTC, mpirvu requested changes

2024-03-25 22:27 UTC, mpirvu commented on runtime/compiler/runtime/CRRuntime.cpp
> +      // At this point the CR RUntime thread should have attached successfully
Typo "RUntime"

2024-03-25 22:27 UTC, mpirvu commented on runtime/compiler/runtime/CRRuntime.cpp
> +   if(javaVM->internalVMFunctions->createThreadWithCategory(&_crRuntimeOSThread,
Space needed after `if`

2024-03-25 22:27 UTC, mpirvu commented on runtime/compiler/runtime/CRRuntime.cpp
> +   if(javaVM->internalVMFunctions->createThreadWithCategory(&_crRuntimeOSThread,
Immediately after the thread gets created, it is possible for the crRuntime thread to execute all its code and be stuck in a busy loop in process() with CRRuntimeMonitor in hand and FAILED_TO_ATTACH state.

2024-03-26 15:03 UTC, dsouzai commented on runtime/compiler/runtime/CRRuntime.cpp
> +#if defined(J9VM_OPT_CRIU_SUPPORT)
Yeah I can do that; I didn't realize that was a possibility.

2024-03-26 19:11 UTC, dsouzai commented
@mpirvu made the requested changes. Also as we discussed offline, because the CRRuntimeThread only executes `process()` if the return value of `internalAttachCurrentThread` is `JNI_OK`, the busy loop scenario isn't possible as thing stand.

2024-03-26 19:56 UTC, mpirvu commented on runtime/compiler/control/CMakeLists.txt
> +if(J9VM_OPT_CRIU_SUPPORT)
Shouldn't `compiler/runtime/CRRuntime.cpp` be here as well?

2024-03-26 19:58 UTC, mpirvu commented on runtime/compiler/control/CMakeLists.txt
> +if(J9VM_OPT_CRIU_SUPPORT)
Oh, it's a different directory

2024-03-26 19:59 UTC, mpirvu approved these changes
LGTM

2024-03-26 20:01 UTC, mpirvu commented
jenkins test all jdk17

2024-03-26 20:03 UTC, mpirvu commented
jenkins test sanity all jdk17

2024-03-27 13:24 UTC, dsouzai commented
aarch64 test failure 
```
[2024-03-26T23:11:38.529Z] FAILED test targets:
[2024-03-26T23:11:38.529Z] 	cmdLineTester_criu_jitserverPostRestore_3
```
is due to
```
[2024-03-26T22:15:26.157Z] Output from test:
[2024-03-26T22:15:26.157Z]  [OUT] start running script
[2024-03-26T22:15:26.157Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2024-03-26T22:15:26.157Z]  [OUT] export LD_BIND_NOT=on
[2024-03-26T22:15:26.157Z]  [OUT] Starting /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_linux_Personal_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=52366 -XX:JITServerHealthProbePort=55016 
[2024-03-26T22:15:26.157Z]  [OUT] JITSERVER DOES NOT EXIST
[2024-03-26T22:15:26.157Z]  [OUT] finished script
[2024-03-26T22:15:26.157Z]  [ERR] can't bind server address: Address already in use
[2024-03-26T22:15:26.157Z]  [ERR] Failed to open health socket on port 55016
```

2024-03-27 22:14 UTC, mpirvu commented
jenkins test sanity alinux64 jdk17

2024-03-28 04:34 UTC, dsouzai commented
All tests have passed; this should be good to merge now.

2024-03-28 12:11 UTC, merged