Relocate the code for the ensureHashed Classes
eclipse-openj9/openj9 pull request #19859
Opened 2024-07-15 20:03 UTC by ChengJin01

The changes move the code specific to the ensureHashed Classes
to EnsureHashedConfig.cpp so as to make room for the code with
initialization at startup.

Signed-off-by: ChengJin01 <jincheng@ca.ibm.com>

2024-07-15 20:07 UTC, ChengJin01 commented
This is not related to #19714 but I'd like to relocate the code there to tide them up for the initialization related code at startup before make any changes in `jvminit.c` for #19714.

2024-07-15 20:09 UTC, ChengJin01 commented
The PR has been verified in personal builds on all supported platforms.

Reviewer: @keithc-ca
FYI: @tajila, @pshipton

2024-07-16 13:29 UTC, keithc-ca requested changes

2024-07-16 13:46 UTC, ChengJin01 commented on runtime/vm/CMakeLists.txt
> +	EnsureHashedConfig.cpp
Fixed.

2024-07-16 13:46 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +			/* we failed the allocation. */
Fixed everywhere.

2024-07-16 13:46 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +	if (TRUE == isAdd) {
Fixed.

2024-07-16 13:46 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +	char *className = option;
Fixed.

2024-07-16 13:46 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +	if (0 == strcmp(option, "")) {
Fixed.

2024-07-16 13:46 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +				sizeof(char*),
Fixed.

2024-07-16 13:46 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +	hashtableEntry = (J9UTF8 *)j9mem_allocate_memory(classNameLength + sizeof(J9UTF8_LENGTH(hashtableEntry)), OMRMEM_CATEGORY_VM);
Fixed.

2024-07-16 13:47 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +				hashtableEntry = NULL;
Fixed.

2024-07-16 13:47 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +		nextOption = scan_to_delim(PORTLIB, &cursor, ',');
Fixed.

2024-07-16 13:47 UTC, ChengJin01 commented on runtime/vm/EnsureHashedConfig.cpp
> +			nextOption = NULL;
Fixed.

2024-07-16 15:30 UTC, keithc-ca commented
Jenkins test sanity amac jdk21

2024-07-16 18:13 UTC, merged