Enforce maximum name size during class loading
eclipse-openj9/openj9 pull request #19898
Opened 2024-07-22 16:48 UTC by theresa-m

Class names are stored as a UTF8 string and length is represented by
 two bytes

2024-07-22 18:06 UTC, keithc-ca requested changes

2024-07-22 18:20 UTC, theresa-m commented on runtime/nls/j9vm/j9vm.nls
> +J9NLS_VM_CLASS_NAME_EXCEEDS_MAX_LENGTH=Class name exceeds maximum length
Okay. What does this achieve?

2024-07-22 19:34 UTC, pshipton commented on runtime/nls/j9vm/j9vm.nls
> +J9NLS_VM_CLASS_NAME_EXCEEDS_MAX_LENGTH=Class name exceeds maximum length
It ensures the NLS messages have the same ids in all the streams. Which probably isn't all that important in this case, but easy to fix.

2024-07-22 19:34 UTC, pshipton commented
We'll need a similar change in 0.47 as well.

2024-07-22 19:35 UTC, pshipton commented on runtime/nls/j9vm/j9vm.nls
> +J9NLS_VM_CLASS_NAME_EXCEEDS_MAX_LENGTH=Class name exceeds maximum length
It would make it much easier to add translations to 0.46 if for some reason we decided to do that.

2024-07-23 14:36 UTC, theresa-m commented on runtime/nls/j9vm/j9vm.nls
> +J9NLS_VM_CLASS_NAME_EXCEEDS_MAX_LENGTH=Class name exceeds maximum length
Thanks. I have added them to my change.

2024-07-23 14:47 UTC, pshipton approved these changes

2024-07-23 15:12 UTC, keithc-ca approved these changes

2024-07-23 15:13 UTC, merged