Allow array types for Serializeable and Cloneable
eclipse-openj9/openj9 pull request #19938
Opened 2024-07-30 16:50 UTC by theresa-m

2024-07-31 14:09 UTC, theresa-m commented
fyi @ChengJin01 after this change the output from TestInterface in https://github.com/eclipse-openj9/openj9/issues/19756 is:

```
Error: Unable to initialize main class TestInterface
Caused by: java.lang.VerifyError: JVMVRFY021 thrown object not throwable; class=TestInterface, method=method1()V, pc=7
Exception Details:
  Location:
    TestInterface.method1()V @7: JBinvokeinterface
  Reason:
    Type '[LTestInterface$A;' (current frame, stack[0]) is not assignable to 'TestInterface$I'
  Current Frame:
    bci: @7
    flags: { }
    locals: { '[LTestInterface$A;' }
    stack: { '[LTestInterface$A;' }
```

2024-07-31 14:19 UTC, ChengJin01 commented
@theresa-m. Please double-check all related test suites (internal & open) to ensure no other issue is introduced with the updated code.

2024-08-01 13:37 UTC, ChengJin01 requested changes

2024-08-01 13:37 UTC, ChengJin01 commented on runtime/bcverify/rtverify.c
> +				if (bc == JBinvokeinterface) {
It's better to change it to `JBinvokeinterface == bc`.

2024-08-01 13:47 UTC, ChengJin01 approved these changes
LGTM.

2024-08-01 14:07 UTC, tajila approved these changes

2024-08-01 14:07 UTC, tajila commented
jenkins test sanity alinux64 jdk17

2024-08-01 21:41 UTC, merged