SCC check for jar and zip string endings
eclipse-openj9/openj9 pull request #20179
Opened 2024-09-17 20:02 UTC by theresa-m

2024-09-17 20:31 UTC, pshipton commented
jenkins compile plinux jdk17

2024-09-20 14:33 UTC, keithc-ca requested changes

2024-09-20 14:33 UTC, keithc-ca commented on runtime/jcl/common/shared.c
> +			|| (NULL != strstr(pathChars,"!/")) || (NULL != strstr(pathChars,"!\\"))
What ensures that `pathLen >= 4` so `pathLen - 4` is a reasonable offset?

The type of `endsWith` should be `const char *` so no cast is necessary.

Missing spaces after `,` and both sides of `-`.

2024-09-30 20:16 UTC, theresa-m commented
Discussed with @hangshao0 and @pshipton that it is not worth continuing with this change.

2024-09-30 20:16 UTC, closed without merging