Change offset check to 0x7
eclipse-openj9/openj9 pull request #20323
Opened 2024-10-09 18:08 UTC by matthewhall2

Offset verification for inlineAtomicLong was being verified to be a multiple of 4, however from testing, a multiple of 8 is needed: for compressed refs, the header size is 4 and the offset of the field is 4. For non-compressed refs, the header size is 8 and the field offset is 8.

2024-10-17 15:21 UTC, r30shah commented
@matthewhall2  as this one is fixing/ closing that issue, please use appropriate commit message. See  https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md#example-commits

2024-10-17 15:31 UTC, r30shah requested changes
Change itself looks good to me. Please update the commit message and body with some useful information.

2024-10-17 18:04 UTC, matthewhall2 commented
> Change itself looks good to me. Please update the commit message and body with some useful information.

done

2024-10-17 18:38 UTC, r30shah commented
Please follow up on https://github.com/eclipse-openj9/openj9/pull/20323#issuecomment-2419847586

2024-10-18 19:00 UTC, r30shah requested changes
I would use following commit title and the body.

```
Fix fieldAlignment check for AtomicLong on Z

"value" field in AtomicLong is of type "long" and should be
aligned to 8-byte boundary.
Check field alignment for AtomicLong was incorrectly checking if the
offset of the field is aligned to 4 byte boundary instead of 8.
This commit fixes that.

Closes: https://github.com/eclipse-openj9/openj9/issues/20235
```

Please also update PR title and description, also if you are using the above commit message, please ensure the body width to 72. 

Tag me once you make above changes, I will launch sanity changes.

2024-10-18 21:07 UTC, r30shah commented
> "value" field for in AtomicLong is of type "long" and therefore should be aligned to 8-byte boundary.

value field in in AtomicLong...

2024-10-18 21:08 UTC, r30shah requested changes
> "value" field for in AtomicLong is of type "long" and therefore should be aligned to 8-byte boundary.

Seems like a minor grammatical error `value field in AtomicLong...`

2024-10-18 22:14 UTC, r30shah approved these changes
LGTM

2024-10-18 22:15 UTC, r30shah commented
jenkins test sanity zlinux jdk11,jdk21

2024-10-21 00:23 UTC, r30shah commented
The failure seen in JDK11 is same as https://github.com/eclipse-openj9/openj9/issues/14948, launching JDK11 test again.

2024-10-21 00:23 UTC, r30shah commented
jenkins test sanity zlinux jdk11

2024-10-21 12:57 UTC, r30shah commented
All test passed,merging.

2024-10-21 12:57 UTC, merged