Update NLS translations
eclipse-openj9/openj9 pull request #20556
Opened 2024-11-08 22:11 UTC by pshipton

2024-11-08 22:14 UTC, pshipton commented
Fixing the line endings.

2024-11-11 15:30 UTC, keithc-ca requested changes

2024-11-11 16:52 UTC, pshipton commented on runtime/nls/shrc/j9shr_ja.nls
> +J9NLS_CC_OSPAGE_SIZE_MISMATCH_V1=\u30aa\u30da\u30ec\u30fc\u30c6\u30a3\u30f3\u30b0\u30fb\u30b7\u30b9\u30c6\u30e0\u306e\u30da\u30fc\u30b8\u30fb\u30b5\u30a4\u30ba%1$zu \u306f\u3001\u30ec\u30a4\u30e4%3$d
How do you know? Google translate offers the following translation:
The operating system page size, %1$zu, differs from the page size, %2$zu, of the system on which the layer %3$d cache was created.

2024-11-11 16:58 UTC, pshipton commented on runtime/nls/shrc/j9shr_zh.nls
> +J9NLS_CC_OSPAGE_SIZE_MISMATCH_V1=\u64cd\u4f5c\u7cfb\u7edf\u7684\u9875\u9762\u5927\u5c0f (%1$zu) \u4e0e\u521b\u5efa\u5c42%3$d\u7f13\u5b58\u7684\u7cfb\u7edf\u7684\u9875\u9762\u5927\u5c0f (%2$zu) \u4e0d
I don't know. Google translate gives the following, which seem fine.
This also applies to the next comment "Spaces around %3$d?", zh and zh_CN are the same translation.
The operating system's page size (%1$zu) is different from the system's page size (%2$zu) on which the tier %3$d cache was created.

2024-11-11 17:05 UTC, pshipton commented on runtime/nls/shrc/j9shr_de.nls
> +J9NLS_CC_OSPAGE_SIZE_MISMATCH_V1=Die Seitengr\u00f6\u00dfe%1$zu) des Betriebssystems unterscheidet sich von der Seitengr\u00f6\u00dfe%2$zu) des Systems, auf dem der Cache der Schicht %3$d erstellt wi
Updated.

2024-11-11 17:05 UTC, pshipton commented on runtime/nls/shrc/j9shr_ko.nls
> +J9NLS_CC_OSPAGE_SIZE_MISMATCH_V1=\uc6b4\uc601 \uccb4\uc81c\uc758 \ud398\uc774\uc9c0 \ud06c\uae30(%1$zu)\uac00 %3$d \uce90\uc2dc \uacc4\uce35\uc774 \ub9cc\ub4e4\uc5b4\uc9c0\ub294 \uc2dc\uc2a4\ud15c\uc
Updated.

2024-11-11 17:12 UTC, keithc-ca commented on runtime/nls/shrc/j9shr_ja.nls
> +J9NLS_CC_OSPAGE_SIZE_MISMATCH_V1=\u30aa\u30da\u30ec\u30fc\u30c6\u30a3\u30f3\u30b0\u30fb\u30b7\u30b9\u30c6\u30e0\u306e\u30da\u30fc\u30b8\u30fb\u30b5\u30a4\u30ba%1$zu \u306f\u3001\u30ec\u30a4\u30e4%3$d
Fair enough.

2024-11-11 17:15 UTC, keithc-ca commented on runtime/nls/shrc/j9shr_zh.nls
> +J9NLS_CC_OSPAGE_SIZE_MISMATCH_V1=\u64cd\u4f5c\u7cfb\u7edf\u7684\u9875\u9762\u5927\u5c0f (%1$zu) \u4e0e\u521b\u5efa\u5c42%3$d\u7f13\u5b58\u7684\u7cfb\u7edf\u7684\u9875\u9762\u5927\u5c0f (%2$zu) \u4e0d
I don't really know either, but, as you say, Google seems to think it's fine.

2024-11-11 17:16 UTC, keithc-ca commented on runtime/nls/shrc/j9shr_zh_CN.nls
> +J9NLS_CC_OSPAGE_SIZE_MISMATCH_V1=\u64cd\u4f5c\u7cfb\u7edf\u7684\u9875\u9762\u5927\u5c0f (%1$zu) \u4e0e\u521b\u5efa\u5c42%3$d\u7f13\u5b58\u7684\u7cfb\u7edf\u7684\u9875\u9762\u5927\u5c0f (%2$zu) \u4e0d
Google translate suggests this is ok as well.

2024-11-11 17:27 UTC, keithc-ca approved these changes

2024-11-11 17:28 UTC, keithc-ca commented
Jenkins compile amac jdk21

2024-11-11 17:43 UTC, pshipton commented
I can squash before this is merged.

2024-11-11 17:52 UTC, keithc-ca commented
The [build](https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_mac_Personal/243) passed: I'll wait for you to squash or tell me you've decided against doing so.

2024-11-11 17:53 UTC, pshipton commented
Squashed.

2024-11-11 18:06 UTC, merged