Print actual string arguments with -Xtrace (part 2)
eclipse-openj9/openj9 pull request #20662
Opened 2024-11-21 15:49 UTC by h3110n3rv3

The changes reflect the feature request https://github.com/eclipse-openj9/openj9/issues/16416.

Adding cmdline option to specify string argument length.
-Xtrace:maxstringlength=[0-128]
maxstringlength takes an unsigned integer value from 0 to 128
If maxstringlength = 0 or unspecified, default to address printing.
Other invalid inputs result in the input error.

There will be subsequent PR for tests (part 3).

Signed-off-by: Nick Kamal <<nick.kamal@ibm.com>>

2024-11-21 15:58 UTC, h3110n3rv3 commented
@TobiAjila could you please review for comments/concerns/feedback? Thanks

2024-11-28 14:31 UTC, tajila commented on runtime/rastrace/method_trace.c
> +			unsigned int strArgLength = methodStrArgLength == 0 ? DEFAULT_STRING_LENGTH : methodStrArgLength;
if string length is zero, then we should go back to the old behaviour

2024-11-28 16:22 UTC, tajila commented on runtime/rastrace/method_trace.c
> +		if (clazz == J9VMJAVALANGSTRING_OR_NULL(vm) &&
The && should be on the left.

```
if (clazz == J9VMJAVALANGSTRING_OR_NULL(vm) 
&& (0 != methodStrArgLength)
) {
```

see https://github.com/eclipse-omr/omr/blob/master/doc/CodingStandard.md#formatting-conditions

2024-11-28 16:23 UTC, tajila commented on runtime/rastrace/method_trigger.c
> +	if ((0 > value) ||
same here, formatting issue

2024-12-04 16:22 UTC, tajila commented on runtime/rastrace/j9rastrace.h
> +#define RAS_METHOD_STRING_LENGTH_KEYWORD    "METHODSTRARGLEN"
maybe "MAXSTRINGLENGTHINMETHODPARAMETER"

2024-12-04 16:23 UTC, tajila commented on runtime/rastrace/j9rastrace.h
> +#define RAS_METHOD_STRING_LENGTH_KEYWORD    "METHODSTRARGLEN"
then `RAS_MAX_STRING_LENGTH_IN_METHOD_PARAMTER`

2024-12-04 16:24 UTC, tajila approved these changes

2024-12-04 16:24 UTC, tajila commented
@keithc-ca Please review these changes

2024-12-04 22:20 UTC, keithc-ca requested changes

2024-12-04 22:20 UTC, keithc-ca commented on runtime/oti/j9trace.h
> +	unsigned int    methodStrArgLength;
Suggest this new field should be named `maxStringLength` (for consistency with the keyword).

2024-12-04 22:20 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +	if (getParmNumber(str) != 1) {
Constants on the left of `==` and `!=`, please.

2024-12-04 22:20 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +	const char *p;
Declare one local at a time, and initialize each; `p` is not a very descriptive name, even `parm` would be better.
```c
	int value = 0;
	int length = 0;
	omr_error_t rc = OMR_ERROR_NONE;
	const char *parm = NULL;
```

2024-12-04 22:20 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +	}
I think this is redundant, given the value check below.

2024-12-04 22:20 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +	return OMR_ERROR_NONE;
Suggest using the "between" idiom for this range check (inverted):
```c
	if ((0 <= value) && (value <= RAS_MAX_STRING_LENGTH_LIMIT)) {
		RAS_GLOBAL_FROM_JAVAVM(maxStringLength, vm) = (unsigned int)value;
		return OMR_ERROR_NONE;
	}
```

2024-12-04 22:20 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +	vaReportJ9VMCommandLineError(PORTLIB, "methodstrarglen takes an unsigned integer value from 1 to %d", MAX_STRING_LENGTH);
The name should match the keyword (`maxstringlength`).

2024-12-04 22:20 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +			&& j9_cmdla_stricmp((char *)methodRule->entryAction->name, "jstacktrace") == 0) {
If you want to improve this, the final `) {` goes on a line by itself, constants go on the left of `==` and `!=` and parentheses are missing:
```c
		if ((NULL != methodRule->entryAction)
			&& (NULL != methodRule->entryAction->name)
			&& (0 == j9_cmdla_stricmp((char *)methodRule->entryAction->name, "jstacktrace"))
		) {
```
Similar comment for lines 704-705.

2024-12-04 22:20 UTC, keithc-ca commented on runtime/rastrace/method_trace.c
>  			char utf8Buffer[128];
This should use the limit from the header file:
```c
			char utf8Buffer[RAS_MAX_STRING_LENGTH_LIMIT + 1];
```

2024-12-04 22:20 UTC, keithc-ca commented on runtime/rastrace/method_trace.c
> +		const unsigned int methodStrArgLength = ((RasGlobalStorage *)thr->javaVM->j9rasGlobalStorage)->methodStrArgLength;
This should use `vm` instead of `thr->javaVM`.

2024-12-04 22:36 UTC, keithc-ca commented on runtime/rastrace/j9rastrace.h
> +#define RAS_MAX_STRING_LENGTH_KEYWORD    "MAXSTRINGLENGTHINMETHODPARAMETER"
Actually, the limit should be defined in `j9trace.h` along with the default length which should be applied in `dmpsup.c` when the `RasGlobalStorage` object is allocated.

`j9trace.h`:
```c
/*
 * Default and maximum values for RasGlobalStorage.maxStringLength.
 */
#define RAS_MAX_STRING_LENGTH_DEFAULT  32
#define RAS_MAX_STRING_LENGTH_LIMIT   128
```
`dmpsup.c`:
```c
		memset(vm->j9rasGlobalStorage, '\0', sizeof(RasGlobalStorage));
		vm->j9rasGlobalStorage->maxStringLength = RAS_MAX_STRING_LENGTH_DEFAULT;
```

2024-12-09 17:37 UTC, keithc-ca requested changes

2024-12-09 17:37 UTC, keithc-ca commented on runtime/rasdump/dmpsup.c
>  					memset (vm->j9rasGlobalStorage, '\0', sizeof(RasGlobalStorage));
While you're here, please remove the unwanted space after `memset`.

2024-12-09 17:37 UTC, keithc-ca commented on runtime/rastrace/method_trace.c
> +		const unsigned int maxStringLength = ((RasGlobalStorage *)vm->j9rasGlobalStorage)->maxStringLength;
This should use `RAS_GLOBAL_FROM_JAVAVM`:
```c
		const unsigned int maxStringLength = RAS_GLOBAL_FROM_JAVAVM(maxStringLength, vm);
```

2024-12-09 17:37 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> + * returns     - JNI return code
Please correct this documetation:
* it isn't just about arguments; string return values are traced as well
* there's no parameter named 'thr'

2024-12-09 17:37 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +	const char *param;
Locals should be initialized:
```c
	const char *param = NULL;
```

2024-12-09 17:37 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +	vaReportJ9VMCommandLineError(PORTLIB, "maxstringlength takes an unsigned integer value from 1 to %d", RAS_MAX_STRING_LENGTH_LIMIT);
I think "unsigned" is redundant here; please just remove it.

2024-12-09 17:37 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +		if ((NULL != methodRule->entryAction)
No trailing whitespace, please.

2024-12-10 21:37 UTC, keithc-ca commented
Jenkins test sanity.functional amac jdk11

2024-12-10 22:12 UTC, keithc-ca commented
The output of `-Xtrace:help` should mention the new option.

For the record, testing is underway at https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/6690.

2024-12-10 23:04 UTC, keithc-ca commented on runtime/rastrace/method_trigger.c
> +	vaReportJ9VMCommandLineError(PORTLIB, "maxstringlength takes an integer value from 1 to %d", RAS_MAX_STRING_LENGTH_LIMIT);
The lower bound is 0, not 1.

2024-12-16 14:47 UTC, tajila approved these changes

2024-12-16 14:47 UTC, tajila commented
jenkins test sanity alinux jdk21

2024-12-16 14:48 UTC, tajila commented
jenkins test sanity alinux64 jdk21

2024-12-16 14:48 UTC, tajila commented
jenkins test sanity win jdk8

2024-12-16 16:38 UTC, tajila commented
jenkins test sanity alinux64 jdk21

2024-12-17 13:11 UTC, tajila commented
jenkins test sanity win jdk8

2024-12-17 13:11 UTC, tajila commented
jenkins test sanity plinux jdk8

2024-12-17 16:26 UTC, merged

2025-01-02 18:57 UTC, keithc-ca commented
> The output of `-Xtrace:help` should mention the new option.

This doesn't appear to have been addressed.