WIP: Print actual String arguments with Xtrace part 3
eclipse-openj9/openj9 pull request #20681
Opened 2024-11-26 20:48 UTC by h3110n3rv3

The changes reflect the feature request https://github.com/eclipse-openj9/openj9/issues/16416 - part 3 following https://github.com/eclipse-openj9/openj9/issues/20662

cmdline tests for -Xtrace:methodstrarglen

Closes: [#16416](https://github.com/eclipse-openj9/openj9/issues/16416)
Signed-off-by: Nick Kamal <nick.kamal@ibm.com>

2024-12-17 19:33 UTC, tajila commented
@theresa-m Please review these changes

2024-12-18 15:31 UTC, theresa-m commented on test/functional/cmdLineTests/xtraceTests/build.xml
> +  Copyright IBM Corp. and others 2020
Please update the copyright date to 2024.

2024-12-18 16:10 UTC, theresa-m requested changes

2024-12-23 15:42 UTC, theresa-m requested changes

2024-12-23 15:42 UTC, theresa-m commented on test/functional/cmdLineTests/xtraceTests/playlist.xml
> +Copyright IBM Corp. and others 2020
The year also needs to be updated here.

2024-12-23 15:42 UTC, theresa-m commented on test/functional/cmdLineTests/xtraceTests/xtraceTests.xml
> +	Copyright IBM Corp. and others 2016
and here

2024-12-24 15:35 UTC, theresa-m approved these changes

2024-12-29 22:36 UTC, tajila approved these changes

2024-12-29 22:36 UTC, tajila commented
jenkins test sanity alinux64 jdk17

2025-01-02 14:10 UTC, merged