Support Java behaviour w.r.t fmin/fmax/dmin/dmax on Z
eclipse-openj9/openj9 pull request #20716
Opened 2024-11-29 15:43 UTC by matthewhall2

- Enables inlining of Math.max/Math.min functions for floats and doubles
- Implements Java standard
  - +0 compares as strictly greater than -0
  - if the first arg is a NaN, returns the NaN unchanged. If only the second arg is a NaN, returns that NaN unchanged

Uses SIMD instructions for floats on z14+, and for doubles on z13+ (fixes errors on z13 machines that were seen after https://github.com/eclipse-openj9/openj9/pull/20530). 

https://github.ibm.com/runtimes/openj9-jit-z/issues/935#issuecomment-98667018

depends on https://github.com/eclipse-omr/omr/pull/7572

[vmfarm](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=82594)
[vmfarm w recognizedmethodtests](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=82653)

2024-12-03 14:15 UTC, matthewhall2 commented
please review @r30shah

2024-12-03 19:26 UTC, r30shah requested changes
Minor nitpicks, changes looks ok to me. Please fix this and relaunch the build in internal farm again for sanity.

2024-12-03 19:26 UTC, r30shah commented on test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaLangMath.java
> - * Copyright IBM Corp. and others 2019
Original copy right was correct, there was not issue with space here.

2024-12-03 19:26 UTC, r30shah commented on test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaLangMath.java
> +     * Tests the constant corner cases defined by the {@link Math.sqrt} method.
It should be consistent for comments. 
```
/**
 *
 *
 */
```

2024-12-03 19:26 UTC, r30shah commented on test/functional/JIT_Test/src/jit/test/recognizedMethod/TestMathUtils.java
> +* Copyright IBM Corp. and others 2024
Please fix the space here. Check the copyright in other files.

2024-12-03 20:31 UTC, r30shah approved these changes
LGTM, I will wait for OMR changes to propagate before launching tests.

2024-12-03 20:44 UTC, matthewhall2 commented
> Minor nitpicks, changes looks ok to me. Please fix this and relaunch the build in internal farm again for sanity.

Thanks @r30shah 
[vmfarm run](https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34501/)

2024-12-06 14:52 UTC, r30shah commented
@matthewhall2  Can you resolve the merge conflict? I see that your OMR changes have been propagated to openj9-omr so we can target to merge this today

2024-12-06 15:02 UTC, matthewhall2 commented
> @matthewhall2 Can you resolve the merge conflict? I see that your OMR changes have been propagated to openj9-omr so we can target to merge this today

done. Running internal sanity checks again

2024-12-06 15:04 UTC, r30shah commented
Jenkins test sanity jdk11,jdk17,jdk21 zlinux

2024-12-06 15:04 UTC, r30shah approved these changes

2024-12-06 15:08 UTC, r30shah commented
jenkins test sanity zlinux jdk11,jdk21

2024-12-06 18:13 UTC, matthewhall2 commented
still waiting on the [sanity run](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=83149) @r30shah. will let you know when it finishes (the only failures right now are for x86)

2024-12-06 21:36 UTC, r30shah commented
All the tests have been on jenkins passes. Merging this based on the the sanity run build from https://github.com/eclipse-openj9/openj9/pull/20716#issuecomment-2523891718 and https://github.com/eclipse-openj9/openj9/pull/20716#issuecomment-2515514780.

@matthewhall2  We should keep monitor OpenJ9 Jenkins build and internal builds in case something pop-up.

2024-12-06 21:36 UTC, merged