WIP: Make disable CAS and CAE options consistant
eclipse-openj9/openj9 pull request #20721
Opened 2024-11-29 22:24 UTC by IBMJimmyk

Changes TR_DisableCASInlining envvar to disable inlining Unsafe compareAndSwap on all platforms. This used to only work on X and would also disable inlining compareAndExchange at the same time. Now it only disables inlining compareAndSwap.

Renames TR_DisableCAEIntrinsic envvar to TR_DisableCAEIntrinsic and it disables inlining Unsafe compareAndExchange on all platforms.

Envvars are now checked in fewer locations and set an option bit instead. The following methods were added to support this: getSupportsInlineUnsafeCompareAndSet
setSupportsInlineUnsafeCompareAndSet
getSupportsInlineUnsafeCompareAndExchange
setSupportsInlineUnsafeCompareAndExchange

These methods are used to indicate support for inlining CAS/CAE and also to query for suppport.

2024-11-29 22:24 UTC, IBMJimmyk commented
Currently in the middle of testing. So far things look good and problems are not expected.

2024-12-23 21:13 UTC, IBMJimmyk commented
Everything should be good now. Unfortunately, this changes a little bit on every platform so I'll need a review from a few different people.

@hzongaro Can you look over the Common and X changes?
@zl-wang Can you look over the Power changes?
@r30shah Can you look over the Z changes?
@knn-k Can you look over the Arm changes?

No rush on this change since it is mostly code clean up so getting a review after the holidays is okay.

2024-12-24 00:29 UTC, knn-k approved these changes
AArch64 changes look good to me.

2025-01-06 18:23 UTC, hzongaro approved these changes
I think the x86 and common changes look good.  Thanks!

2025-01-07 03:18 UTC, r30shah requested changes

2025-01-07 03:18 UTC, r30shah commented on runtime/compiler/codegen/J9CodeGenerator.cpp
> +      if ((self()->comp()->target().cpu.isX86() || self()->comp()->target().cpu.isPower() || self()->comp()->target().cpu.isZ()) &&
Do we still need this platform check here. By default `getSupportsInlineUnsafeCompareAndSet` / `getSupportsInlineUnsafeCompareAndExchange` should return false if it does not support on platform. So I think it should only check for `useCompressedPointers` and `useOldCompareAndSwapObject` here and where you are checking for CompareAndSet / Compare and Exchange, it should do the codegen query.

2025-01-13 19:40 UTC, zl-wang approved these changes
LGTM

2025-01-13 19:41 UTC, zl-wang commented
Jenkins test sanity all jdk23

2025-01-14 03:27 UTC, merged