Generate inline class equality test
eclipse-openj9/openj9 pull request #20801
Opened 2024-12-10 17:42 UTC by matthewhall2

Adds class equality check as first check; calls C Helper in OOL section on fail.

This change is not yet enabled, but will be enabled once remaining inlined tests are added.

[vm-farm this branch (mz,xz)](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=83425)

The following are tests run on a branch with this change enabled:
[vm-farm test branch (mz, xz)](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=83422)

2024-12-10 19:44 UTC, matthewhall2 commented
@r30shah please review

2024-12-10 19:58 UTC, r30shah requested changes
Overall looks good, some minor comments

2024-12-10 19:58 UTC, r30shah commented on runtime/compiler/z/codegen/J9TreeEvaluator.cpp
> +   cg->generateDebugCounter(TR::DebugCounter::debugCounterName(comp, "checkCastStats/(%s)/Equal", comp->signature()),1,TR::DebugCounter::Undetermined);
This debug counter name is not suitable for Class.isAssignableFrom. For the equality test, I feel we do not need separate function as it is only generating one instruction.

2024-12-10 19:58 UTC, r30shah commented on runtime/compiler/z/codegen/J9TreeEvaluator.cpp
> +   generateS390LabelInstruction(cg, TR::InstOpCode::label, node, successLabel, deps);
Your internal control flow ends at doneLabel, successLabel does not need register dependency condition.

2024-12-10 19:58 UTC, r30shah commented on runtime/compiler/z/codegen/J9TreeEvaluator.cpp
> +   genInlineClassEqualityTest(node, cg, cg->comp(), toClassReg, fromClassReg, successLabel);
First instruction from which internal control flow starts is the instruction generated for class equality -  make sure that you generate a label instruction before that and mark it as start internal control flow,.

2024-12-10 19:58 UTC, r30shah commented on runtime/compiler/z/codegen/J9TreeEvaluator.cpp
>     generateS390LabelInstruction(cg, TR::InstOpCode::label, node, doneLabel, deps);
Your internal control flow ends here. Mark this to end ICF

2024-12-10 21:01 UTC, r30shah requested changes

2024-12-10 21:01 UTC, r30shah commented on runtime/compiler/z/codegen/J9TreeEvaluator.cpp
> +   generateS390LabelInstruction(cg, TR::InstOpCode::label, node, successLabel, deps);
Register dependency should be attached to the end of internal control flow label. We do not need it here.

2024-12-10 21:23 UTC, r30shah commented
jenkins test sanity zlinux jdk11,jdk21

2024-12-11 02:37 UTC, r30shah commented
I am merging this change based on the testing done by @matthewhall2 .

2024-12-11 02:37 UTC, merged

2024-12-11 14:24 UTC, matthewhall2 commented
> Looks good to me, Please share the snippet from Instruction selection log

here you go
 ```
[     0x3ff6c242ac0]                          LG      &GPR_0086, Shadow[<javaLangClassFromClass>] 48(GPR_0082)
 [     0x3ff6c242b90]                          LG      GPR_0084, Shadow[<classFromJavaLangClass>] 8(&GPR_0086)
 [     0x3ff6c242f20]                          LG      &GPR_0090, Shadow[<javaLangClassFromClass>] 48(GPR_0080)
 [     0x3ff6c242ff0]                          LG      GPR_0088, Shadow[<classFromJavaLangClass>] 8(&GPR_0090)
 [     0x3ff6c2432b0]                          Label L0047:     # (Start of internal control flow)
 [     0x3ff6c243390]                          CGRJ    GPR_0088,GPR_0084,Label L0046,BH(mask=0x8),
 [     0x3ff6c243480]                          BRC     NOP(0xf), Outlined Label L0044
 [     0x3ff6c246fa0]                          Label L0046:
 [     0x3ff6c247080]                          LGHI    GPR_0132,0x1
 [     0x3ff6c2477d0]                          assocreg
 [     0x3ff6c247210]                          Label L0045:     # (End of internal control flow)
 POST:
 {AssignAny:GPR_0084:R} {AssignAny:GPR_0088:R} {AssignAny:GPR_0132:R}

------------------------------

 [     0x3ff6c2435b0]                          Outlined Label L0044:
 [     0x3ff6c245920]                          LGR     GPR_0131,GPR13
 [     0x3ff6c245ea0]                          STG     GPR5,#411 32(GPR13)
 [     0x3ff6c246560]                          assocreg
  PRE:
 {GPR2:GPR_0131:R} {GPR3:GPR_0084:R} {GPR4:GPR_0088:R}
 [     0x3ff6c245f70]                          BRASL   GPR_0098,0x0000000000000000
 POST:
 [     0x3ff6c246ca0]                          assocreg
 [     0x3ff6c2466f0]                          LG      GPR5,#412 32(GPR13)
```