Return from park immediately for negative time since epoch
eclipse-openj9/openj9 pull request #20802
Opened 2024-12-10 18:38 UTC by theresa-m

If the deadline since epoch given to Unsafe.park is negative the calculation of `mills` could overflow. To prevent this set the return code to `J9THREAD_TIMED_OUT ` for negative deadlines since they have always passed.

Related to: https://github.com/eclipse-openj9/openj9/issues/17135

2024-12-10 21:16 UTC, keithc-ca requested changes

2024-12-10 21:16 UTC, keithc-ca commented on runtime/vm/threadpark.cpp
> +				*/
Please correct the indentation of lines 54, 55.

2024-12-10 21:16 UTC, keithc-ca commented on runtime/vm/threadpark.cpp
> +				if ()
I assume this was added in error.

2024-12-10 21:16 UTC, keithc-ca commented on runtime/vm/threadpark.cpp
>  	if ((0 != timeout) || (timeoutIsEpochRelative)) {
While you're here, please remove the redundant parentheses:
```c
	if ((0 != timeout) || timeoutIsEpochRelative) {
```

2024-12-10 21:16 UTC, keithc-ca commented on runtime/vm/threadpark.cpp
> +					/*Trc_JCL_park_timeIsInPast(vmThread, timeNow);*/
Please add spaces in the comment (see line 47):
```c
					/* Trc_JCL_park_timeIsInPast(vmThread, timeNow); */
```

2024-12-10 21:17 UTC, keithc-ca commented
Rather than "negative" the description should say "non-positive", unless the intent was "negative" in which case the code needs to be corrected.

2025-01-02 16:29 UTC, tajila commented
@keithc-ca Please take another look at this

2025-01-02 21:00 UTC, keithc-ca commented
Jenkins test sanity osx jdk8

2025-01-03 03:47 UTC, keithc-ca approved these changes

2025-01-03 15:36 UTC, tajila approved these changes

2025-01-03 15:37 UTC, merged