Include AccessController methods for jit JDK 24+
eclipse-openj9/openj9 pull request #20859
Opened 2024-12-19 20:25 UTC by theresa-m

As I understand it these methods were excluded due to security manager use. Since AccessController.doPrivileged methods don't use the security manager in 24+ they can be re-included.

Related: https://github.com/eclipse-openj9/openj9/issues/20563

2025-01-13 15:56 UTC, theresa-m commented
@dsouzai can you take a look at this change or advise on the best person to review?

2025-01-13 18:49 UTC, keithc-ca requested changes

2025-01-13 18:49 UTC, keithc-ca commented on runtime/compiler/env/j9method.cpp
> +#endif /* (24 < JAVA_SPEC_VERSION) */
Parentheses are not needed, normally the operands would be reversed and we want `>=` to include Java 24 as the title suggests:
```c
#if JAVA_SPEC_VERSION >= 24
```

2025-01-13 21:14 UTC, hzongaro commented on runtime/compiler/env/j9method.cpp
> +#if (24 < JAVA_SPEC_VERSION)
If I'm understanding [`isCompilable`](https://github.com/eclipse-openj9/openj9/blob/a8dcdd8a8d2cd3d330a43e9d50c31b496679cbf4/runtime/compiler/env/j9method.cpp#L773-L775) correctly, any method whose signature is found in `excludeArray` will not be compiled.  So if we want these methods to be compiled for JDK 24 or later, but not for JDK 23 or earlier, I think the condition should be:

```
#if (JAVA_SPEC_VERSION < 24)
```

Sorry if I'm misunderstanding what this is doing!

2025-01-13 21:15 UTC, hzongaro commented on runtime/compiler/env/j9method.cpp
> +#if (24 < JAVA_SPEC_VERSION)
Sorry - that suggestion should have omitted the parentheses, as @keithc-ca pointed out.

2025-01-13 21:17 UTC, hzongaro commented
By the way, may I suggest you remove the words "As I understand it" from the start of the commit comment?

2025-01-13 21:32 UTC, keithc-ca commented on runtime/compiler/env/j9method.cpp
> +#if (24 < JAVA_SPEC_VERSION)
That is consistent with how I read `isCompilable()`. I think my confusion stems from the use of the word "include"; those methods are included in a table of exclusions - maybe the commit message should avoid the terms "include" and "exclude" and better express the goal of this change: to allow the JIT compiler to consider compiling those methods for Java 24+.

So the code should read:
```c
#if JAVA_SPEC_VERSION < 24
```

2025-01-14 15:44 UTC, keithc-ca commented
Please update the commit message and the title here to spell JIT properly and consistently.
Please also squash the repeated spaces in the commit message.

2025-01-14 18:19 UTC, keithc-ca commented
That crash looks like https://github.com/eclipse-openj9/openj9/issues/20870. About your only recourse is to try again.

2025-01-14 18:27 UTC, theresa-m commented
> https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_sanity.functional_x86-64_linux_Personal_testList_0/9/consoleFull

Interesting... I've tried twice in a personal build and once locally and I got the same crash all three times. Perhaps I can try again when the issue is resolved.

2025-01-15 15:00 UTC, theresa-m commented
My latest builds contains only known failures that are not related to this change https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_sanity.functional_x86-64_linux_Personal/10/

2025-01-15 15:07 UTC, keithc-ca approved these changes

2025-01-15 16:12 UTC, hzongaro approved these changes

2025-01-16 16:56 UTC, hzongaro commented
JDK 24 test failures for alinux and plinux were all known problems.  I will rerun the JDK 24 xlinux testing which failed to run to completion.

Jenkins test sanity.functional,sanity.openjdk xlinux jdk24

2025-01-17 03:29 UTC, hzongaro commented
Trying xlinux JDK 24 testing once more. . . .

Jenkins test sanity.functional,sanity.openjdk xlinux jdk24

2025-01-17 18:28 UTC, hzongaro commented
In [JDK 24 xlinux sanity.functional testing](https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.functional_x86-64_linux_Personal/3/):
- Failure running `testSCCMLTests1_openj9_0` doesn't seem to be a known problem, but it doesn't appear to be related to this change.
- Other failures are known problems

The [JDK 24 xlinux sanity.openjdk failures](https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.openjdk_x86-64_linux_Personal/3/) all appear to be due to known problems.

Merging.

2025-01-17 18:28 UTC, merged